// Generated by tools/make_voice.py. Do not edit by hand.
window.AUDIO_FILES = {
"s0-l0": {
"url": "audio/s0-l0.m4a",
"voice": "Rishi",
"h": "2f8473b0be8f"
},
"s0-l1": {
"url": "audio/s0-l1.m4a",
"voice": "Daniel",
"h": "1e5afde03706"
},
"s0-l2": {
"url": "audio/s0-l2.m4a",
"voice": "Rishi",
"h": "9c07caa25921"
},
"s0-l3": {
"url": "audio/s0-l3.m4a",
"voice": "Daniel",
"h": "7c612e8e743b"
},
"s0-l4": {
"url": "audio/s0-l4.m4a",
"voice": "Rishi",
"h": "f77a3a74026f"
},
"s0-l5": {
"url": "audio/s0-l5.m4a",
"voice": "Daniel",
"h": "5d69a6939f1c"
},
"s0-l6": {
"url": "audio/s0-l6.m4a",
"voice": "Rishi",
"h": "52a00bd53e4d"
},
"s0-l7": {
"url": "audio/s0-l7.m4a",
"voice": "Daniel",
"h": "9c73d6f0b668"
},
"s0-l8": {
"url": "audio/s0-l8.m4a",
"voice": "Rishi",
"h": "366525cf4ec5"
},
"s0-l9": {
"url": "audio/s0-l9.m4a",
"voice": "Daniel",
"h": "badd94fcfac3"
},
"s0-l10": {
"url": "audio/s0-l10.m4a",
"voice": "Rishi",
"h": "56e80ef463b8"
},
"s0-l11": {
"url": "audio/s0-l11.m4a",
"voice": "Daniel",
"h": "cb4dbe50d481"
},
"s0-l12": {
"url": "audio/s0-l12.m4a",
"voice": "Rishi",
"h": "5a2b291c1b55"
},
"s0-l13": {
"url": "audio/s0-l13.m4a",
"voice": "Daniel",
"h": "3f5a8a7a1964"
},
"s1-l0": {
"url": "audio/s1-l0.m4a",
"voice": "Rishi",
"h": "828d0d685461"
},
"s1-l1": {
"url": "audio/s1-l1.m4a",
"voice": "Daniel",
"h": "9ab16971e8bf"
},
"s1-l2": {
"url": "audio/s1-l2.m4a",
"voice": "Rishi",
"h": "6947552d814b"
},
"s1-l3": {
"url": "audio/s1-l3.m4a",
"voice": "Daniel",
"h": "54789cabed68"
},
"s1-l4": {
"url": "audio/s1-l4.m4a",
"voice": "Rishi",
"h": "425d209eeb8d"
},
"s1-l5": {
"url": "audio/s1-l5.m4a",
"voice": "Daniel",
"h": "ea636353948d"
},
"s1-l6": {
"url": "audio/s1-l6.m4a",
"voice": "Rishi",
"h": "3598fcc644bb"
},
"s1-l7": {
"url": "audio/s1-l7.m4a",
"voice": "Daniel",
"h": "44b364d75e6c"
},
"s1-l8": {
"url": "audio/s1-l8.m4a",
"voice": "Rishi",
"h": "827a41e5f9e9"
},
"s1-l9": {
"url": "audio/s1-l9.m4a",
"voice": "Daniel",
"h": "abceffc8be73"
},
"s2-l0": {
"url": "audio/s2-l0.m4a",
"voice": "Samantha",
"h": "6347b70d71b6"
},
"s2-l1": {
"url": "audio/s2-l1.m4a",
"voice": "Daniel",
"h": "806abb8e08c1"
},
"s2-l2": {
"url": "audio/s2-l2.m4a",
"voice": "Daniel",
"h": "e7227ac41238"
},
"s2-l3": {
"url": "audio/s2-l3.m4a",
"voice": "Daniel",
"h": "ee8c314d1e4d"
},
"s2-l4": {
"url": "audio/s2-l4.m4a",
"voice": "Daniel",
"h": "9ac1f317055c"
},
"s2-l5": {
"url": "audio/s2-l5.m4a",
"voice": "Samantha",
"h": "1f8aa7e5b52f"
},
"s2-l6": {
"url": "audio/s2-l6.m4a",
"voice": "Daniel",
"h": "2b1f10706518"
},
"s2-l7": {
"url": "audio/s2-l7.m4a",
"voice": "Samantha",
"h": "7ac988ad833f"
},
"s2-l8": {
"url": "audio/s2-l8.m4a",
"voice": "Daniel",
"h": "7f6bce7a628d"
},
"s3-l1": {
"url": "audio/s3-l1.m4a",
"voice": "Daniel",
"h": "f5d682dc56fd"
},
"s3-l2": {
"url": "audio/s3-l2.m4a",
"voice": "Daniel",
"h": "b73ed69e3590"
},
"s3-l3": {
"url": "audio/s3-l3.m4a",
"voice": "Daniel",
"h": "e3d37f2e6a88"
},
"s3-l5": {
"url": "audio/s3-l5.m4a",
"voice": "Daniel",
"h": "412a749c6a08"
},
"s3-l6": {
"url": "audio/s3-l6.m4a",
"voice": "Daniel",
"h": "2373895b8ced"
},
"s3-l7": {
"url": "audio/s3-l7.m4a",
"voice": "Daniel",
"h": "e02e2341ed2e"
},
"s3-l8": {
"url": "audio/s3-l8.m4a",
"voice": "Karen",
"h": "3f8171ad65f9"
},
"s3-l9": {
"url": "audio/s3-l9.m4a",
"voice": "Daniel",
"h": "639ec4b20c57"
},
"s4-l0": {
"url": "audio/s4-l0.m4a",
"voice": "Rishi",
"h": "31dda7989146"
},
"s4-l1": {
"url": "audio/s4-l1.m4a",
"voice": "Daniel",
"h": "676f2e770e19"
},
"s4-l2": {
"url": "audio/s4-l2.m4a",
"voice": "Daniel",
"h": "8422d4e101d7"
},
"s4-l3": {
"url": "audio/s4-l3.m4a",
"voice": "Daniel",
"h": "00b953d0d1ae"
},
"s4-l4": {
"url": "audio/s4-l4.m4a",
"voice": "Daniel",
"h": "3ca43a620d22"
},
"s4-l5": {
"url": "audio/s4-l5.m4a",
"voice": "Daniel",
"h": "f7d7af480a97"
},
"s4-l6": {
"url": "audio/s4-l6.m4a",
"voice": "Rishi",
"h": "de7627f5d05e"
},
"s4-l7": {
"url": "audio/s4-l7.m4a",
"voice": "Daniel",
"h": "570fbb1a264e"
},
"s5-l0": {
"url": "audio/s5-l0.m4a",
"voice": "Daniel",
"h": "e352d848d819"
},
"s5-l1": {
"url": "audio/s5-l1.m4a",
"voice": "Rishi",
"h": "0bc4e8d52fa7"
},
"s5-l2": {
"url": "audio/s5-l2.m4a",
"voice": "Daniel",
"h": "a497b8d5c6f3"
},
"s5-l3": {
"url": "audio/s5-l3.m4a",
"voice": "Rishi",
"h": "5f156bed8c46"
},
"s5-l4": {
"url": "audio/s5-l4.m4a",
"voice": "Daniel",
"h": "3261566c2419"
},
"s5-l5": {
"url": "audio/s5-l5.m4a",
"voice": "Rishi",
"h": "fda52adff2ac"
},
"s5-l6": {
"url": "audio/s5-l6.m4a",
"voice": "Daniel",
"h": "f64d16be41e2"
},
"s5-l7": {
"url": "audio/s5-l7.m4a",
"voice": "Rishi",
"h": "69cef3055a7a"
},
"s5-l8": {
"url": "audio/s5-l8.m4a",
"voice": "Daniel",
"h": "29314ce1ceb6"
},
"s5-l9": {
"url": "audio/s5-l9.m4a",
"voice": "Rishi",
"h": "b0d8f276f8e5"
},
"s5-l10": {
"url": "audio/s5-l10.m4a",
"voice": "Daniel",
"h": "e6e8f6080444"
},
"s6-l0": {
"url": "audio/s6-l0.m4a",
"voice": "Rishi",
"h": "8779ea80750d"
},
"s6-l1": {
"url": "audio/s6-l1.m4a",
"voice": "Daniel",
"h": "35f631e093f0"
},
"s6-l2": {
"url": "audio/s6-l2.m4a",
"voice": "Rishi",
"h": "5d8f677f1acc"
},
"s6-l3": {
"url": "audio/s6-l3.m4a",
"voice": "Daniel",
"h": "981b14ec7722"
},
"s6-l4": {
"url": "audio/s6-l4.m4a",
"voice": "Rishi",
"h": "bf818dfd1ff1"
},
"s6-l5": {
"url": "audio/s6-l5.m4a",
"voice": "Daniel",
"h": "f1964f2f915a"
},
"s6-l6": {
"url": "audio/s6-l6.m4a",
"voice": "Rishi",
"h": "c932defe177b"
},
"s6-l7": {
"url": "audio/s6-l7.m4a",
"voice": "Daniel",
"h": "41e0f6b22603"
},
"s6-l8": {
"url": "audio/s6-l8.m4a",
"voice": "Rishi",
"h": "bf9a627b9221"
},
"s6-l9": {
"url": "audio/s6-l9.m4a",
"voice": "Daniel",
"h": "3814054c8b5a"
},
"s7-l0": {
"url": "audio/s7-l0.m4a",
"voice": "Rishi",
"h": "fea866540217"
},
"s7-l2": {
"url": "audio/s7-l2.m4a",
"voice": "Daniel",
"h": "4dae2624d34f"
},
"s7-l3": {
"url": "audio/s7-l3.m4a",
"voice": "Daniel",
"h": "546021b8f538"
},
"s7-l4": {
"url": "audio/s7-l4.m4a",
"voice": "Daniel",
"h": "8852992af29f"
},
"s7-l5": {
"url": "audio/s7-l5.m4a",
"voice": "Samantha",
"h": "7d8508cfd8fb"
},
"s7-l6": {
"url": "audio/s7-l6.m4a",
"voice": "Daniel",
"h": "53a0cd506eab"
},
"s7-l7": {
"url": "audio/s7-l7.m4a",
"voice": "Rishi",
"h": "2c8c4aa19adc"
},
"s7-l8": {
"url": "audio/s7-l8.m4a",
"voice": "Daniel",
"h": "ffe1e2a8bb14"
},
"s8-l0": {
"url": "audio/s8-l0.m4a",
"voice": "Samantha",
"h": "85d093c55846"
},
"s8-l1": {
"url": "audio/s8-l1.m4a",
"voice": "Daniel",
"h": "cda67da7da9d"
},
"s8-l2": {
"url": "audio/s8-l2.m4a",
"voice": "Samantha",
"h": "cd4bef87de6f"
},
"s8-l3": {
"url": "audio/s8-l3.m4a",
"voice": "Daniel",
"h": "f179ad3ca9a0"
},
"s8-l4": {
"url": "audio/s8-l4.m4a",
"voice": "Samantha",
"h": "41364f1c6358"
},
"s8-l5": {
"url": "audio/s8-l5.m4a",
"voice": "Daniel",
"h": "c855ae24785e"
},
"s8-l6": {
"url": "audio/s8-l6.m4a",
"voice": "Samantha",
"h": "b7431d2ca342"
},
"s8-l7": {
"url": "audio/s8-l7.m4a",
"voice": "Daniel",
"h": "29f34aeac48f"
},
"s8-l8": {
"url": "audio/s8-l8.m4a",
"voice": "Samantha",
"h": "bd3badb6cc14"
},
"s8-l9": {
"url": "audio/s8-l9.m4a",
"voice": "Daniel",
"h": "ee5f9fb55ad6"
},
"s8-l11": {
"url": "audio/s8-l11.m4a",
"voice": "Samantha",
"h": "1905788f930c"
},
"s8-l12": {
"url": "audio/s8-l12.m4a",
"voice": "Daniel",
"h": "f8693aeae367"
},
"s9-l0": {
"url": "audio/s9-l0.m4a",
"voice": "Rishi",
"h": "ab268a9c35ec"
},
"s9-l1": {
"url": "audio/s9-l1.m4a",
"voice": "Daniel",
"h": "903aff79e4fc"
},
"s9-l2": {
"url": "audio/s9-l2.m4a",
"voice": "Daniel",
"h": "8178b64d1107"
},
"s9-l3": {
"url": "audio/s9-l3.m4a",
"voice": "Rishi",
"h": "0aa44c0395b9"
},
"s9-l4": {
"url": "audio/s9-l4.m4a",
"voice": "Daniel",
"h": "8e515ffb89e7"
},
"s9-l5": {
"url": "audio/s9-l5.m4a",
"voice": "Rishi",
"h": "80229d24d4e6"
},
"s9-l6": {
"url": "audio/s9-l6.m4a",
"voice": "Daniel",
"h": "109b5cd6fce4"
},
"s9-l7": {
"url": "audio/s9-l7.m4a",
"voice": "Rishi",
"h": "159af5581b7f"
},
"s9-l8": {
"url": "audio/s9-l8.m4a",
"voice": "Daniel",
"h": "8c4fea06f38a"
},
"s9-l9": {
"url": "audio/s9-l9.m4a",
"voice": "Rishi",
"h": "a58f274eba3f"
},
"s9-l10": {
"url": "audio/s9-l10.m4a",
"voice": "Daniel",
"h": "72593c1cbcaf"
},
"s9-l11": {
"url": "audio/s9-l11.m4a",
"voice": "Rishi",
"h": "d596bb38cb6f"
},
"s9-l12": {
"url": "audio/s9-l12.m4a",
"voice": "Daniel",
"h": "76480350ed31"
},
"s10-l0": {
"url": "audio/s10-l0.m4a",
"voice": "Samantha",
"h": "1eb0226c9087"
},
"s10-l1": {
"url": "audio/s10-l1.m4a",
"voice": "Daniel",
"h": "2d1a4909ac44"
},
"s10-l2": {
"url": "audio/s10-l2.m4a",
"voice": "Samantha",
"h": "c37b7418991d"
},
"s10-l3": {
"url": "audio/s10-l3.m4a",
"voice": "Daniel",
"h": "98fff5a4afeb"
},
"s10-l4": {
"url": "audio/s10-l4.m4a",
"voice": "Samantha",
"h": "56627eaf2f2f"
},
"s10-l5": {
"url": "audio/s10-l5.m4a",
"voice": "Daniel",
"h": "5aac2036e795"
},
"s10-l6": {
"url": "audio/s10-l6.m4a",
"voice": "Samantha",
"h": "899997291cfe"
},
"s10-l7": {
"url": "audio/s10-l7.m4a",
"voice": "Daniel",
"h": "394db46c9591"
},
"s10-l8": {
"url": "audio/s10-l8.m4a",
"voice": "Samantha",
"h": "ff619d83131d"
},
"s10-l9": {
"url": "audio/s10-l9.m4a",
"voice": "Daniel",
"h": "9fe808a6decd"
},
"s10-l10": {
"url": "audio/s10-l10.m4a",
"voice": "Samantha",
"h": "ca218efa8e26"
},
"s10-l11": {
"url": "audio/s10-l11.m4a",
"voice": "Daniel",
"h": "5bf6b6e490de"
},
"s11-l0": {
"url": "audio/s11-l0.m4a",
"voice": "Daniel",
"h": "e0dc06a97077"
},
"s11-l1": {
"url": "audio/s11-l1.m4a",
"voice": "Samantha",
"h": "59f8fcab07d8"
},
"s11-l3": {
"url": "audio/s11-l3.m4a",
"voice": "Daniel",
"h": "80d41fabdd40"
},
"s11-l4": {
"url": "audio/s11-l4.m4a",
"voice": "Samantha",
"h": "bfac7435590d"
},
"s11-l5": {
"url": "audio/s11-l5.m4a",
"voice": "Daniel",
"h": "f3bc829967d5"
},
"s11-l6": {
"url": "audio/s11-l6.m4a",
"voice": "Daniel",
"h": "6e06dd1d56e5"
},
"s11-l7": {
"url": "audio/s11-l7.m4a",
"voice": "Samantha",
"h": "420af2225147"
},
"s11-l8": {
"url": "audio/s11-l8.m4a",
"voice": "Daniel",
"h": "510f7d3977e8"
},
"s12-l0": {
"url": "audio/s12-l0.m4a",
"voice": "Rishi",
"h": "91a10cacc6df"
},
"s12-l1": {
"url": "audio/s12-l1.m4a",
"voice": "Daniel",
"h": "159e6215bf9f"
},
"s12-l2": {
"url": "audio/s12-l2.m4a",
"voice": "Daniel",
"h": "9f41e4729845"
},
"s12-l3": {
"url": "audio/s12-l3.m4a",
"voice": "Rishi",
"h": "173dff6a22aa"
},
"s12-l4": {
"url": "audio/s12-l4.m4a",
"voice": "Daniel",
"h": "2de7a9361fb7"
},
"s12-l5": {
"url": "audio/s12-l5.m4a",
"voice": "Rishi",
"h": "a9dd02955ece"
},
"s12-l6": {
"url": "audio/s12-l6.m4a",
"voice": "Daniel",
"h": "a0ddcd4a0d94"
},
"s12-l7": {
"url": "audio/s12-l7.m4a",
"voice": "Rishi",
"h": "a537eca922dd"
},
"s12-l8": {
"url": "audio/s12-l8.m4a",
"voice": "Daniel",
"h": "e066f2ecff66"
},
"s13-l0": {
"url": "audio/s13-l0.m4a",
"voice": "Daniel",
"h": "26987af02b3b"
},
"s13-l1": {
"url": "audio/s13-l1.m4a",
"voice": "Tessa",
"h": "8daf0dc05f6b"
},
"s13-l2": {
"url": "audio/s13-l2.m4a",
"voice": "Daniel",
"h": "58ff1c2bd8cc"
},
"s13-l3": {
"url": "audio/s13-l3.m4a",
"voice": "Daniel",
"h": "888f456ccb16"
},
"s13-l4": {
"url": "audio/s13-l4.m4a",
"voice": "Tessa",
"h": "f4ad3d19c811"
},
"s13-l5": {
"url": "audio/s13-l5.m4a",
"voice": "Daniel",
"h": "bfdabd4350f2"
},
"s13-l6": {
"url": "audio/s13-l6.m4a",
"voice": "Tessa",
"h": "e1b045b64ef5"
},
"s13-l7": {
"url": "audio/s13-l7.m4a",
"voice": "Daniel",
"h": "bd179704abad"
},
"s13-l8": {
"url": "audio/s13-l8.m4a",
"voice": "Tessa",
"h": "ce5e7212a712"
},
"s13-l9": {
"url": "audio/s13-l9.m4a",
"voice": "Daniel",
"h": "f64453d29247"
},
"s14-l0": {
"url": "audio/s14-l0.m4a",
"voice": "Daniel",
"h": "f01df462a660"
},
"s14-l1": {
"url": "audio/s14-l1.m4a",
"voice": "Daniel",
"h": "e68e41b6178c"
},
"s14-l2": {
"url": "audio/s14-l2.m4a",
"voice": "Rishi",
"h": "594a885f42cc"
},
"s14-l3": {
"url": "audio/s14-l3.m4a",
"voice": "Daniel",
"h": "f12aa459ef63"
},
"s14-l4": {
"url": "audio/s14-l4.m4a",
"voice": "Rishi",
"h": "eac9f48a417d"
},
"s14-l5": {
"url": "audio/s14-l5.m4a",
"voice": "Daniel",
"h": "119ae2e748d9"
},
"s14-l6": {
"url": "audio/s14-l6.m4a",
"voice": "Daniel",
"h": "939521d4dbe3"
},
"s14-l7": {
"url": "audio/s14-l7.m4a",
"voice": "Rishi",
"h": "052049bfde05"
},
"s14-l8": {
"url": "audio/s14-l8.m4a",
"voice": "Daniel",
"h": "43f8fcb49c55"
},
"s14-l9": {
"url": "audio/s14-l9.m4a",
"voice": "Rishi",
"h": "62516dc15446"
},
"s15-l0": {
"url": "audio/s15-l0.m4a",
"voice": "Samantha",
"h": "b185f4aed96b"
},
"s15-l1": {
"url": "audio/s15-l1.m4a",
"voice": "Rishi",
"h": "4d8bdd7316bd"
},
"s15-l2": {
"url": "audio/s15-l2.m4a",
"voice": "Daniel",
"h": "9aa4e2ec34ae"
},
"s15-l3": {
"url": "audio/s15-l3.m4a",
"voice": "Daniel",
"h": "59729c453f50"
},
"s15-l4": {
"url": "audio/s15-l4.m4a",
"voice": "Samantha",
"h": "48827d1dd7de"
},
"s15-l5": {
"url": "audio/s15-l5.m4a",
"voice": "Rishi",
"h": "2a379a9061d4"
},
"s15-l6": {
"url": "audio/s15-l6.m4a",
"voice": "Daniel",
"h": "76e1fe80999a"
},
"s15-l7": {
"url": "audio/s15-l7.m4a",
"voice": "Rishi",
"h": "2e5890490651"
},
"s15-l8": {
"url": "audio/s15-l8.m4a",
"voice": "Daniel",
"h": "b5957494d29b"
},
"s15-l9": {
"url": "audio/s15-l9.m4a",
"voice": "Samantha",
"h": "c5eefc2ecb0a"
},
"s15-l10": {
"url": "audio/s15-l10.m4a",
"voice": "Daniel",
"h": "aef303d06b50"
},
"c-fx-r1": {
"url": "audio/c-fx-r1.m4a",
"voice": "Moira",
"h": "9f16a3f2b1ac"
},
"c-fx-r2": {
"url": "audio/c-fx-r2.m4a",
"voice": "Moira",
"h": "f57f1df632b1"
},
"c-fx-turn": {
"url": "audio/c-fx-turn.m4a",
"voice": "Moira",
"h": "0b111f1b48d7"
},
"c-fx-good": {
"url": "audio/c-fx-good.m4a",
"voice": "Moira",
"h": "8b65105b81ae"
},
"c-fx-pace": {
"url": "audio/c-fx-pace.m4a",
"voice": "Moira",
"h": "103665dcef0f"
},
"c-fx-pause": {
"url": "audio/c-fx-pause.m4a",
"voice": "Moira",
"h": "b0d58b19da5c"
},
"c-fx-end": {
"url": "audio/c-fx-end.m4a",
"voice": "Moira",
"h": "b4e1653ea228"
},
"c-fx-nospeech": {
"url": "audio/c-fx-nospeech.m4a",
"voice": "Moira",
"h": "b6baee79b751"
},
"c-fx-done1": {
"url": "audio/c-fx-done1.m4a",
"voice": "Moira",
"h": "669c05e67dc9"
},
"c-fx-done2": {
"url": "audio/c-fx-done2.m4a",
"voice": "Moira",
"h": "65429308692e"
},
"c-s0-l1": {
"url": "audio/c-s0-l1.m4a",
"voice": "Moira",
"h": "35c12c7448d2"
},
"c-s0-l3": {
"url": "audio/c-s0-l3.m4a",
"voice": "Moira",
"h": "2c2b1dd0e74f"
},
"c-s0-l5": {
"url": "audio/c-s0-l5.m4a",
"voice": "Moira",
"h": "37c8eb6f5236"
},
"c-s0-l7": {
"url": "audio/c-s0-l7.m4a",
"voice": "Moira",
"h": "06af144f6ddb"
},
"c-s0-l9": {
"url": "audio/c-s0-l9.m4a",
"voice": "Moira",
"h": "4eef628a3cf9"
},
"c-s0-l11": {
"url": "audio/c-s0-l11.m4a",
"voice": "Moira",
"h": "03b2be34f9ac"
},
"c-s0-l13": {
"url": "audio/c-s0-l13.m4a",
"voice": "Moira",
"h": "8e3e25369367"
},
"c-s1-l1": {
"url": "audio/c-s1-l1.m4a",
"voice": "Moira",
"h": "db45c8da1217"
},
"c-s1-l3": {
"url": "audio/c-s1-l3.m4a",
"voice": "Moira",
"h": "fe13b9cab5c0"
},
"c-s1-l5": {
"url": "audio/c-s1-l5.m4a",
"voice": "Moira",
"h": "4dca7274db6c"
},
"c-s1-l7": {
"url": "audio/c-s1-l7.m4a",
"voice": "Moira",
"h": "7b8b9b64ea5d"
},
"c-s1-l9": {
"url": "audio/c-s1-l9.m4a",
"voice": "Moira",
"h": "42f444acd513"
},
"c-s2-l1": {
"url": "audio/c-s2-l1.m4a",
"voice": "Moira",
"h": "0a290a71f678"
},
"c-s2-l2": {
"url": "audio/c-s2-l2.m4a",
"voice": "Moira",
"h": "e53b49fcc0cb"
},
"c-s2-l3": {
"url": "audio/c-s2-l3.m4a",
"voice": "Moira",
"h": "2f5294473599"
},
"c-s2-l4": {
"url": "audio/c-s2-l4.m4a",
"voice": "Moira",
"h": "c1da0da4b1d3"
},
"c-s2-l6": {
"url": "audio/c-s2-l6.m4a",
"voice": "Moira",
"h": "22d3a378c14f"
},
"c-s2-l8": {
"url": "audio/c-s2-l8.m4a",
"voice": "Moira",
"h": "72c1dd48d7bb"
},
"c-s3-l1": {
"url": "audio/c-s3-l1.m4a",
"voice": "Moira",
"h": "b5bb7430bd93"
},
"c-s3-l2": {
"url": "audio/c-s3-l2.m4a",
"voice": "Moira",
"h": "4cf0b235019e"
},
"c-s3-l3": {
"url": "audio/c-s3-l3.m4a",
"voice": "Moira",
"h": "6f431f76d3df"
},
"c-s3-l5": {
"url": "audio/c-s3-l5.m4a",
"voice": "Moira",
"h": "87aa13b615ec"
},
"c-s3-l6": {
"url": "audio/c-s3-l6.m4a",
"voice": "Moira",
"h": "63e5d7badd51"
},
"c-s3-l7": {
"url": "audio/c-s3-l7.m4a",
"voice": "Moira",
"h": "f70cef056bf2"
},
"c-s3-l9": {
"url": "audio/c-s3-l9.m4a",
"voice": "Moira",
"h": "8b4d5c00ad77"
},
"c-s4-l1": {
"url": "audio/c-s4-l1.m4a",
"voice": "Moira",
"h": "073bf3ed84f0"
},
"c-s4-l2": {
"url": "audio/c-s4-l2.m4a",
"voice": "Moira",
"h": "1692fbe5f3b2"
},
"c-s4-l3": {
"url": "audio/c-s4-l3.m4a",
"voice": "Moira",
"h": "b38211490405"
},
"c-s4-l4": {
"url": "audio/c-s4-l4.m4a",
"voice": "Moira",
"h": "8368b22709f2"
},
"c-s4-l5": {
"url": "audio/c-s4-l5.m4a",
"voice": "Moira",
"h": "945d55e2782f"
},
"c-s4-l7": {
"url": "audio/c-s4-l7.m4a",
"voice": "Moira",
"h": "12d63d1f84e9"
},
"c-s5-l0": {
"url": "audio/c-s5-l0.m4a",
"voice": "Moira",
"h": "78bf67548444"
},
"c-s5-l2": {
"url": "audio/c-s5-l2.m4a",
"voice": "Moira",
"h": "b448111ab626"
},
"c-s5-l4": {
"url": "audio/c-s5-l4.m4a",
"voice": "Moira",
"h": "5109558d8e7c"
},
"c-s5-l6": {
"url": "audio/c-s5-l6.m4a",
"voice": "Moira",
"h": "cc6d8d5439f4"
},
"c-s5-l8": {
"url": "audio/c-s5-l8.m4a",
"voice": "Moira",
"h": "4a38621e7df8"
},
"c-s5-l10": {
"url": "audio/c-s5-l10.m4a",
"voice": "Moira",
"h": "62d326be9ead"
},
"c-s6-l1": {
"url": "audio/c-s6-l1.m4a",
"voice": "Moira",
"h": "0367d7bc26b0"
},
"c-s6-l3": {
"url": "audio/c-s6-l3.m4a",
"voice": "Moira",
"h": "c09a88e62725"
},
"c-s6-l5": {
"url": "audio/c-s6-l5.m4a",
"voice": "Moira",
"h": "8ede90f44de9"
},
"c-s6-l7": {
"url": "audio/c-s6-l7.m4a",
"voice": "Moira",
"h": "11ffa8bc1168"
},
"c-s6-l9": {
"url": "audio/c-s6-l9.m4a",
"voice": "Moira",
"h": "a8e4caea177f"
},
"c-s7-l2": {
"url": "audio/c-s7-l2.m4a",
"voice": "Moira",
"h": "e4cba4e01424"
},
"c-s7-l3": {
"url": "audio/c-s7-l3.m4a",
"voice": "Moira",
"h": "965ca92731cb"
},
"c-s7-l4": {
"url": "audio/c-s7-l4.m4a",
"voice": "Moira",
"h": "8c47c87872b5"
},
"c-s7-l6": {
"url": "audio/c-s7-l6.m4a",
"voice": "Moira",
"h": "c2022d841c5e"
},
"c-s7-l8": {
"url": "audio/c-s7-l8.m4a",
"voice": "Moira",
"h": "5e8e33767158"
},
"c-s8-l1": {
"url": "audio/c-s8-l1.m4a",
"voice": "Moira",
"h": "a21cd0ae84ef"
},
"c-s8-l3": {
"url": "audio/c-s8-l3.m4a",
"voice": "Moira",
"h": "bb5501e28ff2"
},
"c-s8-l5": {
"url": "audio/c-s8-l5.m4a",
"voice": "Moira",
"h": "cdac2a2ad9ac"
},
"c-s8-l7": {
"url": "audio/c-s8-l7.m4a",
"voice": "Moira",
"h": "10fa30d05015"
},
"c-s8-l9": {
"url": "audio/c-s8-l9.m4a",
"voice": "Moira",
"h": "1c3160e2c2f9"
},
"c-s8-l12": {
"url": "audio/c-s8-l12.m4a",
"voice": "Moira",
"h": "b3e1ed86f87d"
},
"c-s9-l1": {
"url": "audio/c-s9-l1.m4a",
"voice": "Moira",
"h": "d21a1978b6fd"
},
"c-s9-l2": {
"url": "audio/c-s9-l2.m4a",
"voice": "Moira",
"h": "8030061deb9a"
},
"c-s9-l4": {
"url": "audio/c-s9-l4.m4a",
"voice": "Moira",
"h": "4091c98a1684"
},
"c-s9-l6": {
"url": "audio/c-s9-l6.m4a",
"voice": "Moira",
"h": "3e4ab2ddcf7b"
},
"c-s9-l8": {
"url": "audio/c-s9-l8.m4a",
"voice": "Moira",
"h": "d2100ef80d74"
},
"c-s9-l10": {
"url": "audio/c-s9-l10.m4a",
"voice": "Moira",
"h": "e49f2093509f"
},
"c-s9-l12": {
"url": "audio/c-s9-l12.m4a",
"voice": "Moira",
"h": "6ea7138f53b4"
},
"c-s10-l1": {
"url": "audio/c-s10-l1.m4a",
"voice": "Moira",
"h": "6502c19696a7"
},
"c-s10-l3": {
"url": "audio/c-s10-l3.m4a",
"voice": "Moira",
"h": "5b45063fd8a6"
},
"c-s10-l5": {
"url": "audio/c-s10-l5.m4a",
"voice": "Moira",
"h": "b96da606ebae"
},
"c-s10-l7": {
"url": "audio/c-s10-l7.m4a",
"voice": "Moira",
"h": "ae5b1443b690"
},
"c-s10-l9": {
"url": "audio/c-s10-l9.m4a",
"voice": "Moira",
"h": "71565d80763a"
},
"c-s10-l11": {
"url": "audio/c-s10-l11.m4a",
"voice": "Moira",
"h": "3a1fd05f69b0"
},
"c-s11-l0": {
"url": "audio/c-s11-l0.m4a",
"voice": "Moira",
"h": "6e97faa9a0ab"
},
"c-s11-l3": {
"url": "audio/c-s11-l3.m4a",
"voice": "Moira",
"h": "fdaf34d93c0f"
},
"c-s11-l5": {
"url": "audio/c-s11-l5.m4a",
"voice": "Moira",
"h": "4f8c346c2064"
},
"c-s11-l6": {
"url": "audio/c-s11-l6.m4a",
"voice": "Moira",
"h": "2ed2fda12dcb"
},
"c-s11-l8": {
"url": "audio/c-s11-l8.m4a",
"voice": "Moira",
"h": "c8cf7e616e60"
},
"c-s12-l1": {
"url": "audio/c-s12-l1.m4a",
"voice": "Moira",
"h": "07f00c88b510"
},
"c-s12-l2": {
"url": "audio/c-s12-l2.m4a",
"voice": "Moira",
"h": "7c3112f0bc7b"
},
"c-s12-l4": {
"url": "audio/c-s12-l4.m4a",
"voice": "Moira",
"h": "1da179c765c4"
},
"c-s12-l6": {
"url": "audio/c-s12-l6.m4a",
"voice": "Moira",
"h": "89deed3113bd"
},
"c-s12-l8": {
"url": "audio/c-s12-l8.m4a",
"voice": "Moira",
"h": "daa2d1a7296d"
},
"c-s13-l0": {
"url": "audio/c-s13-l0.m4a",
"voice": "Moira",
"h": "d89728c20dbb"
},
"c-s13-l2": {
"url": "audio/c-s13-l2.m4a",
"voice": "Moira",
"h": "813628bef32f"
},
"c-s13-l3": {
"url": "audio/c-s13-l3.m4a",
"voice": "Moira",
"h": "a399628f86c2"
},
"c-s13-l5": {
"url": "audio/c-s13-l5.m4a",
"voice": "Moira",
"h": "0f632b21c150"
},
"c-s13-l7": {
"url": "audio/c-s13-l7.m4a",
"voice": "Moira",
"h": "b1768b09097f"
},
"c-s13-l9": {
"url": "audio/c-s13-l9.m4a",
"voice": "Moira",
"h": "3505d5fd6dfd"
},
"c-s14-l0": {
"url": "audio/c-s14-l0.m4a",
"voice": "Moira",
"h": "57bad038886c"
},
"c-s14-l1": {
"url": "audio/c-s14-l1.m4a",
"voice": "Moira",
"h": "2019ffbcc37a"
},
"c-s14-l3": {
"url": "audio/c-s14-l3.m4a",
"voice": "Moira",
"h": "7770fe9929e1"
},
"c-s14-l5": {
"url": "audio/c-s14-l5.m4a",
"voice": "Moira",
"h": "82d8a54b516b"
},
"c-s14-l6": {
"url": "audio/c-s14-l6.m4a",
"voice": "Moira",
"h": "7e4c772912c4"
},
"c-s14-l8": {
"url": "audio/c-s14-l8.m4a",
"voice": "Moira",
"h": "251a60828c9e"
},
"c-s15-l2": {
"url": "audio/c-s15-l2.m4a",
"voice": "Moira",
"h": "bab5cc046440"
},
"c-s15-l3": {
"url": "audio/c-s15-l3.m4a",
"voice": "Moira",
"h": "4afd3de018de"
},
"c-s15-l6": {
"url": "audio/c-s15-l6.m4a",
"voice": "Moira",
"h": "8ac842cc424d"
},
"c-s15-l8": {
"url": "audio/c-s15-l8.m4a",
"voice": "Moira",
"h": "3275a32cce5d"
},
"c-s15-l10": {
"url": "audio/c-s15-l10.m4a",
"voice": "Moira",
"h": "63b90cabb18b"
},
"c-lesson0-intro": {
"url": "audio/c-lesson0-intro.m4a",
"voice": "Moira",
"h": "d2bcd72b4192"
},
"c-lesson0-drill": {
"url": "audio/c-lesson0-drill.m4a",
"voice": "Moira",
"h": "5a5815935fec"
},
"c-lesson1-intro": {
"url": "audio/c-lesson1-intro.m4a",
"voice": "Moira",
"h": "45e4b7837bc3"
},
"c-lesson1-drill": {
"url": "audio/c-lesson1-drill.m4a",
"voice": "Moira",
"h": "154624254735"
},
"c-lesson2-intro": {
"url": "audio/c-lesson2-intro.m4a",
"voice": "Moira",
"h": "939081b37355"
},
"c-lesson2-drill": {
"url": "audio/c-lesson2-drill.m4a",
"voice": "Moira",
"h": "8761b7b3bcfc"
},
"c-lesson3-intro": {
"url": "audio/c-lesson3-intro.m4a",
"voice": "Moira",
"h": "fe22c1813f37"
},
"c-lesson3-drill": {
"url": "audio/c-lesson3-drill.m4a",
"voice": "Moira",
"h": "e1ffaa7d46f8"
},
"c-lesson4-intro": {
"url": "audio/c-lesson4-intro.m4a",
"voice": "Moira",
"h": "45b568bf08e2"
},
"c-lesson4-drill": {
"url": "audio/c-lesson4-drill.m4a",
"voice": "Moira",
"h": "ee37a0631b37"
},
"c-lesson5-intro": {
"url": "audio/c-lesson5-intro.m4a",
"voice": "Moira",
"h": "43676f0cc2cc"
},
"c-lesson5-drill": {
"url": "audio/c-lesson5-drill.m4a",
"voice": "Moira",
"h": "4b9492b17ffa"
},
"c-lesson6-intro": {
"url": "audio/c-lesson6-intro.m4a",
"voice": "Moira",
"h": "afdf1d5082ee"
},
"c-lesson6-drill": {
"url": "audio/c-lesson6-drill.m4a",
"voice": "Moira",
"h": "6891de64c3f7"
},
"c-lesson7-intro": {
"url": "audio/c-lesson7-intro.m4a",
"voice": "Moira",
"h": "9c040e26e6f7"
},
"c-lesson7-drill": {
"url": "audio/c-lesson7-drill.m4a",
"voice": "Moira",
"h": "2cb82cba9150"
}
};
