// Generated by tools/make_voice.py. Do not edit by hand.
window.AUDIO_FILES = {
"s0-l0": {
"url": "audio/s0-l0.m4a",
"voice": "am_fenrir",
"h": "663d27490865"
},
"s0-l2": {
"url": "audio/s0-l2.m4a",
"voice": "am_fenrir",
"h": "579920a0b363"
},
"s0-l3": {
"url": "audio/s0-l3.m4a",
"voice": "am_michael",
"h": "4256dfcf8a16"
},
"s0-l4": {
"url": "audio/s0-l4.m4a",
"voice": "am_fenrir",
"h": "72f0a243779a"
},
"s0-l5": {
"url": "audio/s0-l5.m4a",
"voice": "am_michael",
"h": "bffa1a740e2f"
},
"s0-l6": {
"url": "audio/s0-l6.m4a",
"voice": "am_fenrir",
"h": "eff9ac843f1b"
},
"s0-l7": {
"url": "audio/s0-l7.m4a",
"voice": "am_michael",
"h": "165e47af7140"
},
"s0-l8": {
"url": "audio/s0-l8.m4a",
"voice": "am_fenrir",
"h": "104667bc15fd"
},
"s0-l9": {
"url": "audio/s0-l9.m4a",
"voice": "am_michael",
"h": "bcd90d55cabe"
},
"s0-l10": {
"url": "audio/s0-l10.m4a",
"voice": "am_fenrir",
"h": "bbe814cc498c"
},
"s0-l11": {
"url": "audio/s0-l11.m4a",
"voice": "am_michael",
"h": "1bf0cc2d85c2"
},
"s0-l12": {
"url": "audio/s0-l12.m4a",
"voice": "am_fenrir",
"h": "994a6a59dca3"
},
"s0-l13": {
"url": "audio/s0-l13.m4a",
"voice": "am_michael",
"h": "6180c9c54212"
},
"s1-l0": {
"url": "audio/s1-l0.m4a",
"voice": "am_fenrir",
"h": "b88081ba25aa"
},
"s1-l1": {
"url": "audio/s1-l1.m4a",
"voice": "am_michael",
"h": "befae784695e"
},
"s1-l2": {
"url": "audio/s1-l2.m4a",
"voice": "am_fenrir",
"h": "5908f51f2272"
},
"s1-l3": {
"url": "audio/s1-l3.m4a",
"voice": "am_michael",
"h": "29f8753cce6f"
},
"s1-l4": {
"url": "audio/s1-l4.m4a",
"voice": "am_fenrir",
"h": "69511972b598"
},
"s1-l5": {
"url": "audio/s1-l5.m4a",
"voice": "am_michael",
"h": "40f1be236e61"
},
"s1-l6": {
"url": "audio/s1-l6.m4a",
"voice": "am_fenrir",
"h": "7feb2372dee0"
},
"s1-l7": {
"url": "audio/s1-l7.m4a",
"voice": "am_michael",
"h": "4e5886a7d523"
},
"s1-l8": {
"url": "audio/s1-l8.m4a",
"voice": "am_fenrir",
"h": "4acec0df7bf3"
},
"s1-l9": {
"url": "audio/s1-l9.m4a",
"voice": "am_michael",
"h": "02be08436099"
},
"s2-l2": {
"url": "audio/s2-l2.m4a",
"voice": "am_michael",
"h": "481e8dc2ff87"
},
"s2-l3": {
"url": "audio/s2-l3.m4a",
"voice": "am_michael",
"h": "3d615415e9d7"
},
"s2-l4": {
"url": "audio/s2-l4.m4a",
"voice": "am_michael",
"h": "0f71cd2bd9a4"
},
"s2-l5": {
"url": "audio/s2-l5.m4a",
"voice": "af_nicole",
"h": "38a15039977c"
},
"s2-l6": {
"url": "audio/s2-l6.m4a",
"voice": "am_michael",
"h": "e3f6df7ecc68"
},
"s2-l7": {
"url": "audio/s2-l7.m4a",
"voice": "af_nicole",
"h": "66d3449444d4"
},
"s2-l8": {
"url": "audio/s2-l8.m4a",
"voice": "am_michael",
"h": "9e89c4941c22"
},
"s3-l1": {
"url": "audio/s3-l1.m4a",
"voice": "am_michael",
"h": "ca90a2396b67"
},
"s3-l2": {
"url": "audio/s3-l2.m4a",
"voice": "am_michael",
"h": "36ed07142866"
},
"s3-l5": {
"url": "audio/s3-l5.m4a",
"voice": "am_michael",
"h": "de33064018c3"
},
"s3-l6": {
"url": "audio/s3-l6.m4a",
"voice": "am_michael",
"h": "205f92efd0fe"
},
"s3-l7": {
"url": "audio/s3-l7.m4a",
"voice": "am_michael",
"h": "b9ac7ef1cf80"
},
"s3-l8": {
"url": "audio/s3-l8.m4a",
"voice": "bf_emma",
"h": "f7bec2041388"
},
"s3-l9": {
"url": "audio/s3-l9.m4a",
"voice": "am_michael",
"h": "e9bd1a04d06d"
},
"s4-l0": {
"url": "audio/s4-l0.m4a",
"voice": "am_fenrir",
"h": "c4f1a680c7a0"
},
"s4-l1": {
"url": "audio/s4-l1.m4a",
"voice": "am_michael",
"h": "081f569abaa9"
},
"s4-l2": {
"url": "audio/s4-l2.m4a",
"voice": "am_michael",
"h": "3c6531fd00e5"
},
"s4-l3": {
"url": "audio/s4-l3.m4a",
"voice": "am_michael",
"h": "8e55326dc05d"
},
"s4-l4": {
"url": "audio/s4-l4.m4a",
"voice": "am_michael",
"h": "daaa1ce1d695"
},
"s4-l5": {
"url": "audio/s4-l5.m4a",
"voice": "am_michael",
"h": "05ca5f3ca5ea"
},
"s4-l6": {
"url": "audio/s4-l6.m4a",
"voice": "am_fenrir",
"h": "25c8b763cfdd"
},
"s4-l7": {
"url": "audio/s4-l7.m4a",
"voice": "am_michael",
"h": "a2c3aad191be"
},
"s5-l0": {
"url": "audio/s5-l0.m4a",
"voice": "am_michael",
"h": "43f9976584b8"
},
"s5-l1": {
"url": "audio/s5-l1.m4a",
"voice": "am_fenrir",
"h": "13e70d889657"
},
"s5-l2": {
"url": "audio/s5-l2.m4a",
"voice": "am_michael",
"h": "8ae85b128ec6"
},
"s5-l3": {
"url": "audio/s5-l3.m4a",
"voice": "am_fenrir",
"h": "1996d54ee0e1"
},
"s5-l4": {
"url": "audio/s5-l4.m4a",
"voice": "am_michael",
"h": "6e5d347f9dc6"
},
"s5-l5": {
"url": "audio/s5-l5.m4a",
"voice": "am_fenrir",
"h": "ed2463528734"
},
"s5-l6": {
"url": "audio/s5-l6.m4a",
"voice": "am_michael",
"h": "e1b6df6c1565"
},
"s5-l7": {
"url": "audio/s5-l7.m4a",
"voice": "am_fenrir",
"h": "c3453fec48de"
},
"s5-l8": {
"url": "audio/s5-l8.m4a",
"voice": "am_michael",
"h": "ace040d59f61"
},
"s5-l9": {
"url": "audio/s5-l9.m4a",
"voice": "am_fenrir",
"h": "85e0e4589367"
},
"s5-l10": {
"url": "audio/s5-l10.m4a",
"voice": "am_michael",
"h": "d41bd8ebb0d8"
},
"s6-l0": {
"url": "audio/s6-l0.m4a",
"voice": "am_fenrir",
"h": "8d5247e78f11"
},
"s6-l1": {
"url": "audio/s6-l1.m4a",
"voice": "am_michael",
"h": "517f69d14a97"
},
"s6-l2": {
"url": "audio/s6-l2.m4a",
"voice": "am_fenrir",
"h": "2f08ce013fad"
},
"s6-l3": {
"url": "audio/s6-l3.m4a",
"voice": "am_michael",
"h": "c95474ace245"
},
"s6-l4": {
"url": "audio/s6-l4.m4a",
"voice": "am_fenrir",
"h": "ea0118ed0d17"
},
"s6-l5": {
"url": "audio/s6-l5.m4a",
"voice": "am_michael",
"h": "6cac3e2cc0d4"
},
"s6-l6": {
"url": "audio/s6-l6.m4a",
"voice": "am_fenrir",
"h": "a1e871eb10b1"
},
"s6-l7": {
"url": "audio/s6-l7.m4a",
"voice": "am_michael",
"h": "659afeaee2bb"
},
"s6-l8": {
"url": "audio/s6-l8.m4a",
"voice": "am_fenrir",
"h": "b6daaed0a97a"
},
"s6-l9": {
"url": "audio/s6-l9.m4a",
"voice": "am_michael",
"h": "5b9b88fb91c8"
},
"s7-l0": {
"url": "audio/s7-l0.m4a",
"voice": "am_fenrir",
"h": "b416d619373f"
},
"s7-l2": {
"url": "audio/s7-l2.m4a",
"voice": "am_michael",
"h": "ae5176fa6d10"
},
"s7-l3": {
"url": "audio/s7-l3.m4a",
"voice": "am_michael",
"h": "c08e64e19524"
},
"s7-l4": {
"url": "audio/s7-l4.m4a",
"voice": "am_michael",
"h": "120e67f1609b"
},
"s7-l5": {
"url": "audio/s7-l5.m4a",
"voice": "af_bella",
"h": "187493d1e102"
},
"s7-l6": {
"url": "audio/s7-l6.m4a",
"voice": "am_michael",
"h": "3d3a03accad9"
},
"s7-l7": {
"url": "audio/s7-l7.m4a",
"voice": "am_fenrir",
"h": "f3c77d1952f1"
},
"s7-l8": {
"url": "audio/s7-l8.m4a",
"voice": "am_michael",
"h": "000f8857d5d7"
},
"s8-l0": {
"url": "audio/s8-l0.m4a",
"voice": "af_bella",
"h": "1b120cfaa5d4"
},
"s8-l1": {
"url": "audio/s8-l1.m4a",
"voice": "am_michael",
"h": "c92177a1c26d"
},
"s8-l2": {
"url": "audio/s8-l2.m4a",
"voice": "af_bella",
"h": "1f265d14e32e"
},
"s8-l3": {
"url": "audio/s8-l3.m4a",
"voice": "am_michael",
"h": "2a61d89053c9"
},
"s8-l4": {
"url": "audio/s8-l4.m4a",
"voice": "af_bella",
"h": "5384a06ce66e"
},
"s8-l5": {
"url": "audio/s8-l5.m4a",
"voice": "am_michael",
"h": "8316c5e7ad63"
},
"s8-l6": {
"url": "audio/s8-l6.m4a",
"voice": "af_bella",
"h": "dadf1340947d"
},
"s8-l7": {
"url": "audio/s8-l7.m4a",
"voice": "am_michael",
"h": "74b413ad338d"
},
"s8-l8": {
"url": "audio/s8-l8.m4a",
"voice": "af_bella",
"h": "8977c0eed2d8"
},
"s8-l9": {
"url": "audio/s8-l9.m4a",
"voice": "am_michael",
"h": "848e0ae908e5"
},
"s8-l11": {
"url": "audio/s8-l11.m4a",
"voice": "af_bella",
"h": "e7699227ad2e"
},
"s8-l12": {
"url": "audio/s8-l12.m4a",
"voice": "am_michael",
"h": "7c6e74c2ffe8"
},
"s9-l0": {
"url": "audio/s9-l0.m4a",
"voice": "am_fenrir",
"h": "7b93489f9b92"
},
"s9-l1": {
"url": "audio/s9-l1.m4a",
"voice": "am_michael",
"h": "ca1a9c0d9e8e"
},
"s9-l2": {
"url": "audio/s9-l2.m4a",
"voice": "am_michael",
"h": "c098a110eb4c"
},
"s9-l3": {
"url": "audio/s9-l3.m4a",
"voice": "am_fenrir",
"h": "649093a2f288"
},
"s9-l4": {
"url": "audio/s9-l4.m4a",
"voice": "am_michael",
"h": "84546e4e4d87"
},
"s9-l5": {
"url": "audio/s9-l5.m4a",
"voice": "am_fenrir",
"h": "887558fcc527"
},
"s9-l6": {
"url": "audio/s9-l6.m4a",
"voice": "am_michael",
"h": "ecea7c836462"
},
"s9-l7": {
"url": "audio/s9-l7.m4a",
"voice": "am_fenrir",
"h": "b64e37ca6d5e"
},
"s9-l8": {
"url": "audio/s9-l8.m4a",
"voice": "am_michael",
"h": "d560db1679de"
},
"s9-l9": {
"url": "audio/s9-l9.m4a",
"voice": "am_fenrir",
"h": "c972a7b82d85"
},
"s9-l10": {
"url": "audio/s9-l10.m4a",
"voice": "am_michael",
"h": "cf73a8dace89"
},
"s9-l11": {
"url": "audio/s9-l11.m4a",
"voice": "am_fenrir",
"h": "7d0b735e1c7a"
},
"s9-l12": {
"url": "audio/s9-l12.m4a",
"voice": "am_michael",
"h": "0e973d83336f"
},
"s10-l0": {
"url": "audio/s10-l0.m4a",
"voice": "af_bella",
"h": "d5458e25a9b6"
},
"s10-l1": {
"url": "audio/s10-l1.m4a",
"voice": "am_michael",
"h": "c972fe2727fd"
},
"s10-l2": {
"url": "audio/s10-l2.m4a",
"voice": "af_bella",
"h": "d78feaeda630"
},
"s10-l3": {
"url": "audio/s10-l3.m4a",
"voice": "am_michael",
"h": "fb8ff554cc58"
},
"s10-l4": {
"url": "audio/s10-l4.m4a",
"voice": "af_bella",
"h": "2c8c7c3401f7"
},
"s10-l5": {
"url": "audio/s10-l5.m4a",
"voice": "am_michael",
"h": "c19c95341924"
},
"s10-l6": {
"url": "audio/s10-l6.m4a",
"voice": "af_bella",
"h": "dddeef977a13"
},
"s10-l7": {
"url": "audio/s10-l7.m4a",
"voice": "am_michael",
"h": "b1ab6304356b"
},
"s10-l8": {
"url": "audio/s10-l8.m4a",
"voice": "af_bella",
"h": "5d48f625b8be"
},
"s10-l9": {
"url": "audio/s10-l9.m4a",
"voice": "am_michael",
"h": "1efcafab4717"
},
"s10-l10": {
"url": "audio/s10-l10.m4a",
"voice": "af_bella",
"h": "44aeba4f1b5c"
},
"s10-l11": {
"url": "audio/s10-l11.m4a",
"voice": "am_michael",
"h": "aa088e8e67e9"
},
"s11-l0": {
"url": "audio/s11-l0.m4a",
"voice": "am_michael",
"h": "5952aaecb4fd"
},
"s11-l1": {
"url": "audio/s11-l1.m4a",
"voice": "af_bella",
"h": "53c34bcd4808"
},
"s11-l3": {
"url": "audio/s11-l3.m4a",
"voice": "am_michael",
"h": "5ed0af090eba"
},
"s11-l4": {
"url": "audio/s11-l4.m4a",
"voice": "af_bella",
"h": "e6379106f6b2"
},
"s11-l5": {
"url": "audio/s11-l5.m4a",
"voice": "am_michael",
"h": "72d899b11975"
},
"s11-l6": {
"url": "audio/s11-l6.m4a",
"voice": "am_michael",
"h": "3bbdef261523"
},
"s11-l7": {
"url": "audio/s11-l7.m4a",
"voice": "af_bella",
"h": "5212e4017cbe"
},
"s11-l8": {
"url": "audio/s11-l8.m4a",
"voice": "am_michael",
"h": "7f3836818129"
},
"s12-l0": {
"url": "audio/s12-l0.m4a",
"voice": "am_fenrir",
"h": "bf9c638a33b4"
},
"s12-l1": {
"url": "audio/s12-l1.m4a",
"voice": "am_michael",
"h": "aa107f42d597"
},
"s12-l2": {
"url": "audio/s12-l2.m4a",
"voice": "am_michael",
"h": "e10bba86243d"
},
"s12-l3": {
"url": "audio/s12-l3.m4a",
"voice": "am_fenrir",
"h": "9623b304417c"
},
"s12-l4": {
"url": "audio/s12-l4.m4a",
"voice": "am_michael",
"h": "199d369ea702"
},
"s12-l5": {
"url": "audio/s12-l5.m4a",
"voice": "am_fenrir",
"h": "35ed2e63f247"
},
"s12-l6": {
"url": "audio/s12-l6.m4a",
"voice": "am_michael",
"h": "1b3254ae6df2"
},
"s12-l7": {
"url": "audio/s12-l7.m4a",
"voice": "am_fenrir",
"h": "7c1786d26791"
},
"s12-l8": {
"url": "audio/s12-l8.m4a",
"voice": "am_michael",
"h": "edfe544c7576"
},
"s13-l0": {
"url": "audio/s13-l0.m4a",
"voice": "am_michael",
"h": "8aac9aa55480"
},
"s13-l1": {
"url": "audio/s13-l1.m4a",
"voice": "af_bella",
"h": "5758d1d6c9a3"
},
"s13-l2": {
"url": "audio/s13-l2.m4a",
"voice": "am_michael",
"h": "14214cc5e9c1"
},
"s13-l3": {
"url": "audio/s13-l3.m4a",
"voice": "am_michael",
"h": "3a167ba568d0"
},
"s13-l4": {
"url": "audio/s13-l4.m4a",
"voice": "af_bella",
"h": "8e8b4e6bd378"
},
"s13-l5": {
"url": "audio/s13-l5.m4a",
"voice": "am_michael",
"h": "e32055a0abf5"
},
"s13-l6": {
"url": "audio/s13-l6.m4a",
"voice": "af_bella",
"h": "4d75775a16e4"
},
"s13-l7": {
"url": "audio/s13-l7.m4a",
"voice": "am_michael",
"h": "abc922d5450c"
},
"s13-l8": {
"url": "audio/s13-l8.m4a",
"voice": "af_bella",
"h": "854f1563dd2c"
},
"s13-l9": {
"url": "audio/s13-l9.m4a",
"voice": "am_michael",
"h": "69d32fd41584"
},
"s14-l0": {
"url": "audio/s14-l0.m4a",
"voice": "am_michael",
"h": "46f1cb21a7d3"
},
"s14-l1": {
"url": "audio/s14-l1.m4a",
"voice": "am_michael",
"h": "5ebba2c909e6"
},
"s14-l2": {
"url": "audio/s14-l2.m4a",
"voice": "am_fenrir",
"h": "d6569ee0af2b"
},
"s14-l3": {
"url": "audio/s14-l3.m4a",
"voice": "am_michael",
"h": "5a47be7d4007"
},
"s14-l4": {
"url": "audio/s14-l4.m4a",
"voice": "am_fenrir",
"h": "3ef37b7a56b2"
},
"s14-l5": {
"url": "audio/s14-l5.m4a",
"voice": "am_michael",
"h": "720e57c2ddfd"
},
"s14-l6": {
"url": "audio/s14-l6.m4a",
"voice": "am_michael",
"h": "77f300a67f09"
},
"s14-l7": {
"url": "audio/s14-l7.m4a",
"voice": "am_fenrir",
"h": "7b2fef3c845e"
},
"s14-l8": {
"url": "audio/s14-l8.m4a",
"voice": "am_michael",
"h": "708e1ccf29ab"
},
"s14-l9": {
"url": "audio/s14-l9.m4a",
"voice": "am_fenrir",
"h": "3329b261d6f4"
},
"s15-l0": {
"url": "audio/s15-l0.m4a",
"voice": "af_bella",
"h": "03f416ca9df1"
},
"s15-l1": {
"url": "audio/s15-l1.m4a",
"voice": "am_fenrir",
"h": "c5ae479c18b4"
},
"s15-l2": {
"url": "audio/s15-l2.m4a",
"voice": "am_michael",
"h": "42fc83524338"
},
"s15-l3": {
"url": "audio/s15-l3.m4a",
"voice": "am_michael",
"h": "5e7717b9d570"
},
"s15-l4": {
"url": "audio/s15-l4.m4a",
"voice": "af_bella",
"h": "bcdef4841470"
},
"s15-l5": {
"url": "audio/s15-l5.m4a",
"voice": "am_fenrir",
"h": "37a4f6ff670f"
},
"s15-l6": {
"url": "audio/s15-l6.m4a",
"voice": "am_michael",
"h": "1be5a5fc3f99"
},
"s15-l7": {
"url": "audio/s15-l7.m4a",
"voice": "am_fenrir",
"h": "ef75a5953bb9"
},
"s15-l8": {
"url": "audio/s15-l8.m4a",
"voice": "am_michael",
"h": "e30fe368006b"
},
"s15-l9": {
"url": "audio/s15-l9.m4a",
"voice": "af_bella",
"h": "c72eac1b18c8"
},
"s15-l10": {
"url": "audio/s15-l10.m4a",
"voice": "am_michael",
"h": "b48edecc53e8"
},
"l0-p0": {
"url": "audio/l0-p0.m4a",
"voice": "am_michael",
"h": "675d9d2530e6"
},
"l0-d": {
"url": "audio/l0-d.m4a",
"voice": "am_michael",
"h": "36f197eab97f"
},
"l1-p0": {
"url": "audio/l1-p0.m4a",
"voice": "am_michael",
"h": "3c2afd46084e"
},
"l1-d": {
"url": "audio/l1-d.m4a",
"voice": "am_michael",
"h": "02ed7d20e5e9"
},
"l2-p0": {
"url": "audio/l2-p0.m4a",
"voice": "am_michael",
"h": "7809d3e2221a"
},
"l2-d": {
"url": "audio/l2-d.m4a",
"voice": "am_michael",
"h": "85572575c7ae"
},
"l3-p0": {
"url": "audio/l3-p0.m4a",
"voice": "am_michael",
"h": "4c18d35d7ca1"
},
"l3-d": {
"url": "audio/l3-d.m4a",
"voice": "am_michael",
"h": "487254f0854f"
},
"l4-d": {
"url": "audio/l4-d.m4a",
"voice": "am_michael",
"h": "2bee5450e3c8"
},
"l6-p0": {
"url": "audio/l6-p0.m4a",
"voice": "am_michael",
"h": "8600f77487ee"
},
"l6-d": {
"url": "audio/l6-d.m4a",
"voice": "am_michael",
"h": "b0f7b1274201"
},
"l7-p0": {
"url": "audio/l7-p0.m4a",
"voice": "am_michael",
"h": "430342146b6b"
},
"c-fx-r1": {
"url": "audio/c-fx-r1.m4a",
"voice": "af_heart",
"h": "a777faf2abf6"
},
"c-fx-r2": {
"url": "audio/c-fx-r2.m4a",
"voice": "af_heart",
"h": "48a04805cf14"
},
"c-fx-turn": {
"url": "audio/c-fx-turn.m4a",
"voice": "af_heart",
"h": "db11e2b73aec"
},
"c-fx-good": {
"url": "audio/c-fx-good.m4a",
"voice": "af_heart",
"h": "8d297b5b5f5f"
},
"c-fx-pace": {
"url": "audio/c-fx-pace.m4a",
"voice": "af_heart",
"h": "4400c922a044"
},
"c-fx-pause": {
"url": "audio/c-fx-pause.m4a",
"voice": "af_heart",
"h": "5a6eb0d13554"
},
"c-fx-end": {
"url": "audio/c-fx-end.m4a",
"voice": "af_heart",
"h": "6873ba63053a"
},
"c-fx-nospeech": {
"url": "audio/c-fx-nospeech.m4a",
"voice": "af_heart",
"h": "ed4805a844a6"
},
"c-fx-done1": {
"url": "audio/c-fx-done1.m4a",
"voice": "af_heart",
"h": "bf5ca2ebaeba"
},
"c-fx-done2": {
"url": "audio/c-fx-done2.m4a",
"voice": "af_heart",
"h": "a18b7da4ceb8"
},
"c-fx-quiz": {
"url": "audio/c-fx-quiz.m4a",
"voice": "af_heart",
"h": "1341b9a7dbe2"
},
"c-fx-say": {
"url": "audio/c-fx-say.m4a",
"voice": "af_heart",
"h": "02c7d79a55f0"
},
"c-fx-ldone": {
"url": "audio/c-fx-ldone.m4a",
"voice": "af_heart",
"h": "e0e187096e6e"
},
"c-sc0-intro": {
"url": "audio/c-sc0-intro.m4a",
"voice": "af_heart",
"h": "10f00f140021"
},
"c-s0-l1": {
"url": "audio/c-s0-l1.m4a",
"voice": "af_heart",
"h": "a946a76b5aa7"
},
"c-s0-l3": {
"url": "audio/c-s0-l3.m4a",
"voice": "af_heart",
"h": "7dbab00e6242"
},
"c-s0-l5": {
"url": "audio/c-s0-l5.m4a",
"voice": "af_heart",
"h": "e0e652a4080c"
},
"c-s0-l7": {
"url": "audio/c-s0-l7.m4a",
"voice": "af_heart",
"h": "dea761cde054"
},
"c-s0-l9": {
"url": "audio/c-s0-l9.m4a",
"voice": "af_heart",
"h": "e00ea6841ae8"
},
"c-s0-l11": {
"url": "audio/c-s0-l11.m4a",
"voice": "af_heart",
"h": "9a69472f7e9c"
},
"c-s0-l13": {
"url": "audio/c-s0-l13.m4a",
"voice": "af_heart",
"h": "902172e39aff"
},
"c-sc1-intro": {
"url": "audio/c-sc1-intro.m4a",
"voice": "af_heart",
"h": "6a2ddc5ebbc1"
},
"c-s1-l1": {
"url": "audio/c-s1-l1.m4a",
"voice": "af_heart",
"h": "7c3344b5a3a2"
},
"c-s1-l3": {
"url": "audio/c-s1-l3.m4a",
"voice": "af_heart",
"h": "64f8354f500c"
},
"c-s1-l5": {
"url": "audio/c-s1-l5.m4a",
"voice": "af_heart",
"h": "95792ad40d00"
},
"c-s1-l7": {
"url": "audio/c-s1-l7.m4a",
"voice": "af_heart",
"h": "da2e30c25457"
},
"c-s1-l9": {
"url": "audio/c-s1-l9.m4a",
"voice": "af_heart",
"h": "61653943fd92"
},
"c-sc2-intro": {
"url": "audio/c-sc2-intro.m4a",
"voice": "af_heart",
"h": "a962cf0b7db8"
},
"c-s2-l1": {
"url": "audio/c-s2-l1.m4a",
"voice": "af_heart",
"h": "ef77989ce0ab"
},
"c-s2-l2": {
"url": "audio/c-s2-l2.m4a",
"voice": "af_heart",
"h": "8a990a069923"
},
"c-s2-l3": {
"url": "audio/c-s2-l3.m4a",
"voice": "af_heart",
"h": "f43154c8579f"
},
"c-s2-l4": {
"url": "audio/c-s2-l4.m4a",
"voice": "af_heart",
"h": "505970e933ef"
},
"c-s2-l6": {
"url": "audio/c-s2-l6.m4a",
"voice": "af_heart",
"h": "927022b9eb84"
},
"c-s2-l8": {
"url": "audio/c-s2-l8.m4a",
"voice": "af_heart",
"h": "5ec855d423a8"
},
"c-sc3-intro": {
"url": "audio/c-sc3-intro.m4a",
"voice": "af_heart",
"h": "8b664ddae394"
},
"c-s3-l1": {
"url": "audio/c-s3-l1.m4a",
"voice": "af_heart",
"h": "16a6461e64a7"
},
"c-s3-l2": {
"url": "audio/c-s3-l2.m4a",
"voice": "af_heart",
"h": "4132a6964a2e"
},
"c-s3-l3": {
"url": "audio/c-s3-l3.m4a",
"voice": "af_heart",
"h": "54138bb8a8e1"
},
"c-s3-l5": {
"url": "audio/c-s3-l5.m4a",
"voice": "af_heart",
"h": "535f50804a1d"
},
"c-s3-l6": {
"url": "audio/c-s3-l6.m4a",
"voice": "af_heart",
"h": "dddaf1e89d5d"
},
"c-s3-l7": {
"url": "audio/c-s3-l7.m4a",
"voice": "af_heart",
"h": "f2f22c17ad80"
},
"c-s3-l9": {
"url": "audio/c-s3-l9.m4a",
"voice": "af_heart",
"h": "003c8b50dca1"
},
"c-sc4-intro": {
"url": "audio/c-sc4-intro.m4a",
"voice": "af_heart",
"h": "01cd5f6bdbda"
},
"c-s4-l1": {
"url": "audio/c-s4-l1.m4a",
"voice": "af_heart",
"h": "26b09e0d0f65"
},
"c-s4-l2": {
"url": "audio/c-s4-l2.m4a",
"voice": "af_heart",
"h": "61cf217b195b"
},
"c-s4-l3": {
"url": "audio/c-s4-l3.m4a",
"voice": "af_heart",
"h": "33e308da88fa"
},
"c-s4-l4": {
"url": "audio/c-s4-l4.m4a",
"voice": "af_heart",
"h": "28a3588c5f59"
},
"c-s4-l5": {
"url": "audio/c-s4-l5.m4a",
"voice": "af_heart",
"h": "30afd32803e8"
},
"c-s4-l7": {
"url": "audio/c-s4-l7.m4a",
"voice": "af_heart",
"h": "c69a702bed62"
},
"c-sc5-intro": {
"url": "audio/c-sc5-intro.m4a",
"voice": "af_heart",
"h": "1ec8a3718bec"
},
"c-s5-l0": {
"url": "audio/c-s5-l0.m4a",
"voice": "af_heart",
"h": "3c26562f07f6"
},
"c-s5-l2": {
"url": "audio/c-s5-l2.m4a",
"voice": "af_heart",
"h": "69a9ff3f4a59"
},
"c-s5-l4": {
"url": "audio/c-s5-l4.m4a",
"voice": "af_heart",
"h": "e51df5dea89a"
},
"c-s5-l6": {
"url": "audio/c-s5-l6.m4a",
"voice": "af_heart",
"h": "ff1c3cb59176"
},
"c-s5-l8": {
"url": "audio/c-s5-l8.m4a",
"voice": "af_heart",
"h": "a28ecc780153"
},
"c-s5-l10": {
"url": "audio/c-s5-l10.m4a",
"voice": "af_heart",
"h": "365d2e799c7f"
},
"c-sc6-intro": {
"url": "audio/c-sc6-intro.m4a",
"voice": "af_heart",
"h": "8132b381ad66"
},
"c-s6-l1": {
"url": "audio/c-s6-l1.m4a",
"voice": "af_heart",
"h": "bb71b2727d03"
},
"c-s6-l3": {
"url": "audio/c-s6-l3.m4a",
"voice": "af_heart",
"h": "941ae33f8b85"
},
"c-s6-l5": {
"url": "audio/c-s6-l5.m4a",
"voice": "af_heart",
"h": "984ea6a9b98e"
},
"c-s6-l7": {
"url": "audio/c-s6-l7.m4a",
"voice": "af_heart",
"h": "f6af19fea31b"
},
"c-s6-l9": {
"url": "audio/c-s6-l9.m4a",
"voice": "af_heart",
"h": "7380ff4e877b"
},
"c-sc7-intro": {
"url": "audio/c-sc7-intro.m4a",
"voice": "af_heart",
"h": "5d1edc27df53"
},
"c-s7-l2": {
"url": "audio/c-s7-l2.m4a",
"voice": "af_heart",
"h": "787f201b44be"
},
"c-s7-l3": {
"url": "audio/c-s7-l3.m4a",
"voice": "af_heart",
"h": "52e3162f7a00"
},
"c-s7-l4": {
"url": "audio/c-s7-l4.m4a",
"voice": "af_heart",
"h": "f8bd40590ede"
},
"c-s7-l6": {
"url": "audio/c-s7-l6.m4a",
"voice": "af_heart",
"h": "8bc31bd3c8f6"
},
"c-s7-l8": {
"url": "audio/c-s7-l8.m4a",
"voice": "af_heart",
"h": "24e75de7c3c1"
},
"c-sc8-intro": {
"url": "audio/c-sc8-intro.m4a",
"voice": "af_heart",
"h": "b4b404c1a7dd"
},
"c-s8-l1": {
"url": "audio/c-s8-l1.m4a",
"voice": "af_heart",
"h": "22f5f3ac2268"
},
"c-s8-l3": {
"url": "audio/c-s8-l3.m4a",
"voice": "af_heart",
"h": "4b8c365d0c53"
},
"c-s8-l5": {
"url": "audio/c-s8-l5.m4a",
"voice": "af_heart",
"h": "44f0a35cf0eb"
},
"c-s8-l7": {
"url": "audio/c-s8-l7.m4a",
"voice": "af_heart",
"h": "2a00d994ba2f"
},
"c-s8-l9": {
"url": "audio/c-s8-l9.m4a",
"voice": "af_heart",
"h": "d2551c26ec61"
},
"c-s8-l12": {
"url": "audio/c-s8-l12.m4a",
"voice": "af_heart",
"h": "f9796075c97b"
},
"c-sc9-intro": {
"url": "audio/c-sc9-intro.m4a",
"voice": "af_heart",
"h": "284b5f5b3804"
},
"c-s9-l1": {
"url": "audio/c-s9-l1.m4a",
"voice": "af_heart",
"h": "dab8b67343d9"
},
"c-s9-l2": {
"url": "audio/c-s9-l2.m4a",
"voice": "af_heart",
"h": "24d9b06681d5"
},
"c-s9-l4": {
"url": "audio/c-s9-l4.m4a",
"voice": "af_heart",
"h": "35eb284e1166"
},
"c-s9-l6": {
"url": "audio/c-s9-l6.m4a",
"voice": "af_heart",
"h": "0be3268aff03"
},
"c-s9-l8": {
"url": "audio/c-s9-l8.m4a",
"voice": "af_heart",
"h": "7a56bb4b8a50"
},
"c-s9-l10": {
"url": "audio/c-s9-l10.m4a",
"voice": "af_heart",
"h": "963d8e6e190d"
},
"c-s9-l12": {
"url": "audio/c-s9-l12.m4a",
"voice": "af_heart",
"h": "903f21e21728"
},
"c-sc10-intro": {
"url": "audio/c-sc10-intro.m4a",
"voice": "af_heart",
"h": "3e45663a2115"
},
"c-s10-l1": {
"url": "audio/c-s10-l1.m4a",
"voice": "af_heart",
"h": "6182fe713ed7"
},
"c-s10-l3": {
"url": "audio/c-s10-l3.m4a",
"voice": "af_heart",
"h": "4432ef593afc"
},
"c-s10-l5": {
"url": "audio/c-s10-l5.m4a",
"voice": "af_heart",
"h": "1c1a10158c88"
},
"c-s10-l7": {
"url": "audio/c-s10-l7.m4a",
"voice": "af_heart",
"h": "0e9e76ea0fb1"
},
"c-s10-l9": {
"url": "audio/c-s10-l9.m4a",
"voice": "af_heart",
"h": "da3319d7e4ce"
},
"c-s10-l11": {
"url": "audio/c-s10-l11.m4a",
"voice": "af_heart",
"h": "b7270c51c55d"
},
"c-sc11-intro": {
"url": "audio/c-sc11-intro.m4a",
"voice": "af_heart",
"h": "e4f87fc4377d"
},
"c-s11-l0": {
"url": "audio/c-s11-l0.m4a",
"voice": "af_heart",
"h": "0d4c863475d3"
},
"c-s11-l3": {
"url": "audio/c-s11-l3.m4a",
"voice": "af_heart",
"h": "ceb36f8e510b"
},
"c-s11-l5": {
"url": "audio/c-s11-l5.m4a",
"voice": "af_heart",
"h": "b4d94f3f431e"
},
"c-s11-l6": {
"url": "audio/c-s11-l6.m4a",
"voice": "af_heart",
"h": "598f887abaf8"
},
"c-s11-l8": {
"url": "audio/c-s11-l8.m4a",
"voice": "af_heart",
"h": "63f2d5952415"
},
"c-sc12-intro": {
"url": "audio/c-sc12-intro.m4a",
"voice": "af_heart",
"h": "464644dfe744"
},
"c-s12-l1": {
"url": "audio/c-s12-l1.m4a",
"voice": "af_heart",
"h": "8048134234d1"
},
"c-s12-l2": {
"url": "audio/c-s12-l2.m4a",
"voice": "af_heart",
"h": "da75ac0a072a"
},
"c-s12-l4": {
"url": "audio/c-s12-l4.m4a",
"voice": "af_heart",
"h": "de34d7d0b0db"
},
"c-s12-l6": {
"url": "audio/c-s12-l6.m4a",
"voice": "af_heart",
"h": "0183cc0a3ace"
},
"c-s12-l8": {
"url": "audio/c-s12-l8.m4a",
"voice": "af_heart",
"h": "31cc7d7b70f3"
},
"c-sc13-intro": {
"url": "audio/c-sc13-intro.m4a",
"voice": "af_heart",
"h": "9050021c5567"
},
"c-s13-l0": {
"url": "audio/c-s13-l0.m4a",
"voice": "af_heart",
"h": "60b0a35d8cfd"
},
"c-s13-l2": {
"url": "audio/c-s13-l2.m4a",
"voice": "af_heart",
"h": "114f4163062d"
},
"c-s13-l3": {
"url": "audio/c-s13-l3.m4a",
"voice": "af_heart",
"h": "4b602bc7b7b8"
},
"c-s13-l5": {
"url": "audio/c-s13-l5.m4a",
"voice": "af_heart",
"h": "c716be2ec83b"
},
"c-s13-l7": {
"url": "audio/c-s13-l7.m4a",
"voice": "af_heart",
"h": "eb9fb7986294"
},
"c-s13-l9": {
"url": "audio/c-s13-l9.m4a",
"voice": "af_heart",
"h": "1992880cc7e0"
},
"c-sc14-intro": {
"url": "audio/c-sc14-intro.m4a",
"voice": "af_heart",
"h": "4921137fb598"
},
"c-s14-l0": {
"url": "audio/c-s14-l0.m4a",
"voice": "af_heart",
"h": "3e79a48b7ac8"
},
"c-s14-l1": {
"url": "audio/c-s14-l1.m4a",
"voice": "af_heart",
"h": "f43a951f1559"
},
"c-s14-l3": {
"url": "audio/c-s14-l3.m4a",
"voice": "af_heart",
"h": "88b5f09997f9"
},
"c-s14-l5": {
"url": "audio/c-s14-l5.m4a",
"voice": "af_heart",
"h": "ccf321a01eea"
},
"c-s14-l6": {
"url": "audio/c-s14-l6.m4a",
"voice": "af_heart",
"h": "3b2adc44d789"
},
"c-s14-l8": {
"url": "audio/c-s14-l8.m4a",
"voice": "af_heart",
"h": "94f482b8c430"
},
"c-sc15-intro": {
"url": "audio/c-sc15-intro.m4a",
"voice": "af_heart",
"h": "27bb39d759d5"
},
"c-s15-l2": {
"url": "audio/c-s15-l2.m4a",
"voice": "af_heart",
"h": "c3784e7ab9e1"
},
"c-s15-l3": {
"url": "audio/c-s15-l3.m4a",
"voice": "af_heart",
"h": "da659b6ec54b"
},
"c-s15-l6": {
"url": "audio/c-s15-l6.m4a",
"voice": "af_heart",
"h": "4bf980e2f7e5"
},
"c-s15-l8": {
"url": "audio/c-s15-l8.m4a",
"voice": "af_heart",
"h": "afb8b3344dfa"
},
"c-s15-l10": {
"url": "audio/c-s15-l10.m4a",
"voice": "af_heart",
"h": "148ae9d0eba5"
},
"c-lesson0-intro": {
"url": "audio/c-lesson0-intro.m4a",
"voice": "af_heart",
"h": "13d905dcac8d"
},
"c-lesson0-drill": {
"url": "audio/c-lesson0-drill.m4a",
"voice": "af_heart",
"h": "1d0dc981565d"
},
"c-lesson0-rule": {
"url": "audio/c-lesson0-rule.m4a",
"voice": "af_heart",
"h": "1fd28e858beb"
},
"c-lesson0-p0-note": {
"url": "audio/c-lesson0-p0-note.m4a",
"voice": "af_heart",
"h": "af00738f7748"
},
"c-lesson0-p1-note": {
"url": "audio/c-lesson0-p1-note.m4a",
"voice": "af_heart",
"h": "ac4c5286d8dd"
},
"c-lesson1-intro": {
"url": "audio/c-lesson1-intro.m4a",
"voice": "af_heart",
"h": "0edf29a5ae06"
},
"c-lesson1-drill": {
"url": "audio/c-lesson1-drill.m4a",
"voice": "af_heart",
"h": "b91450c4bedc"
},
"c-lesson1-rule": {
"url": "audio/c-lesson1-rule.m4a",
"voice": "af_heart",
"h": "ad00eaa33fee"
},
"c-lesson1-p0-note": {
"url": "audio/c-lesson1-p0-note.m4a",
"voice": "af_heart",
"h": "d15248c4b96c"
},
"c-lesson1-p1-note": {
"url": "audio/c-lesson1-p1-note.m4a",
"voice": "af_heart",
"h": "261ab03d1b38"
},
"c-lesson2-intro": {
"url": "audio/c-lesson2-intro.m4a",
"voice": "af_heart",
"h": "2274bceb0cf7"
},
"c-lesson2-drill": {
"url": "audio/c-lesson2-drill.m4a",
"voice": "af_heart",
"h": "a39bf8b01b41"
},
"c-lesson2-rule": {
"url": "audio/c-lesson2-rule.m4a",
"voice": "af_heart",
"h": "8cf35b0a7c00"
},
"c-lesson2-p0-note": {
"url": "audio/c-lesson2-p0-note.m4a",
"voice": "af_heart",
"h": "4607feba5ed5"
},
"c-lesson2-p1-note": {
"url": "audio/c-lesson2-p1-note.m4a",
"voice": "af_heart",
"h": "660851e222fd"
},
"c-lesson3-intro": {
"url": "audio/c-lesson3-intro.m4a",
"voice": "af_heart",
"h": "21f52579c86d"
},
"c-lesson3-drill": {
"url": "audio/c-lesson3-drill.m4a",
"voice": "af_heart",
"h": "0b8bbeee7204"
},
"c-lesson3-rule": {
"url": "audio/c-lesson3-rule.m4a",
"voice": "af_heart",
"h": "959f1fc5a20f"
},
"c-lesson3-p0-note": {
"url": "audio/c-lesson3-p0-note.m4a",
"voice": "af_heart",
"h": "fe638ef06009"
},
"c-lesson3-p1-note": {
"url": "audio/c-lesson3-p1-note.m4a",
"voice": "af_heart",
"h": "215bd3cefa62"
},
"c-lesson3-p2-note": {
"url": "audio/c-lesson3-p2-note.m4a",
"voice": "af_heart",
"h": "40633a8643ad"
},
"c-lesson4-intro": {
"url": "audio/c-lesson4-intro.m4a",
"voice": "af_heart",
"h": "e9f9ac3f7701"
},
"c-lesson4-drill": {
"url": "audio/c-lesson4-drill.m4a",
"voice": "af_heart",
"h": "fa91178de911"
},
"c-lesson4-rule": {
"url": "audio/c-lesson4-rule.m4a",
"voice": "af_heart",
"h": "58f8af0057be"
},
"c-lesson4-p0-note": {
"url": "audio/c-lesson4-p0-note.m4a",
"voice": "af_heart",
"h": "d0c46d64eb51"
},
"c-lesson4-p1-note": {
"url": "audio/c-lesson4-p1-note.m4a",
"voice": "af_heart",
"h": "f6e61389f896"
},
"c-lesson5-intro": {
"url": "audio/c-lesson5-intro.m4a",
"voice": "af_heart",
"h": "f49cd45539ee"
},
"c-lesson5-drill": {
"url": "audio/c-lesson5-drill.m4a",
"voice": "af_heart",
"h": "bc2c82f6fb26"
},
"c-lesson5-rule": {
"url": "audio/c-lesson5-rule.m4a",
"voice": "af_heart",
"h": "bec160dffa24"
},
"c-lesson5-p0-note": {
"url": "audio/c-lesson5-p0-note.m4a",
"voice": "af_heart",
"h": "dadb1c3777f7"
},
"c-lesson5-p1-note": {
"url": "audio/c-lesson5-p1-note.m4a",
"voice": "af_heart",
"h": "b482da8bc667"
},
"c-lesson5-p2-note": {
"url": "audio/c-lesson5-p2-note.m4a",
"voice": "af_heart",
"h": "37c6a4abb439"
},
"c-lesson6-intro": {
"url": "audio/c-lesson6-intro.m4a",
"voice": "af_heart",
"h": "7a2d24317aa4"
},
"c-lesson6-drill": {
"url": "audio/c-lesson6-drill.m4a",
"voice": "af_heart",
"h": "c3d94e5b899c"
},
"c-lesson6-rule": {
"url": "audio/c-lesson6-rule.m4a",
"voice": "af_heart",
"h": "74c777681676"
},
"c-lesson6-p0-note": {
"url": "audio/c-lesson6-p0-note.m4a",
"voice": "af_heart",
"h": "a60cf8091011"
},
"c-lesson6-p1-note": {
"url": "audio/c-lesson6-p1-note.m4a",
"voice": "af_heart",
"h": "88c287b7e753"
},
"c-lesson6-p2-note": {
"url": "audio/c-lesson6-p2-note.m4a",
"voice": "af_heart",
"h": "410ef00eda9e"
},
"c-lesson7-intro": {
"url": "audio/c-lesson7-intro.m4a",
"voice": "af_heart",
"h": "431b6685a800"
},
"c-lesson7-drill": {
"url": "audio/c-lesson7-drill.m4a",
"voice": "af_heart",
"h": "90d6c059fc4b"
},
"c-lesson7-rule": {
"url": "audio/c-lesson7-rule.m4a",
"voice": "af_heart",
"h": "c206c1262c23"
},
"c-lesson7-p0-note": {
"url": "audio/c-lesson7-p0-note.m4a",
"voice": "af_heart",
"h": "b75fae0b0a96"
},
"c-lesson7-p1-note": {
"url": "audio/c-lesson7-p1-note.m4a",
"voice": "af_heart",
"h": "2c522306dd0f"
}
};
