// Generated by tools/make_voice.py. Do not edit by hand.
window.AUDIO_FILES = {
"s0-l0": {
"url": "audio/s0-l0.m4a",
"voice": "am_fenrir",
"h": "663d27490865"
},
"s0-l2": {
"url": "audio/s0-l2.m4a",
"voice": "am_fenrir",
"h": "579920a0b363"
},
"s0-l3": {
"url": "audio/s0-l3.m4a",
"voice": "am_michael",
"h": "4256dfcf8a16"
},
"s0-l4": {
"url": "audio/s0-l4.m4a",
"voice": "am_fenrir",
"h": "72f0a243779a"
},
"s0-l5": {
"url": "audio/s0-l5.m4a",
"voice": "am_michael",
"h": "bffa1a740e2f"
},
"s0-l6": {
"url": "audio/s0-l6.m4a",
"voice": "am_fenrir",
"h": "eff9ac843f1b"
},
"s0-l7": {
"url": "audio/s0-l7.m4a",
"voice": "am_michael",
"h": "165e47af7140"
},
"s0-l8": {
"url": "audio/s0-l8.m4a",
"voice": "am_fenrir",
"h": "104667bc15fd"
},
"s0-l9": {
"url": "audio/s0-l9.m4a",
"voice": "am_michael",
"h": "bcd90d55cabe"
},
"s0-l10": {
"url": "audio/s0-l10.m4a",
"voice": "am_fenrir",
"h": "bbe814cc498c"
},
"s0-l11": {
"url": "audio/s0-l11.m4a",
"voice": "am_michael",
"h": "1bf0cc2d85c2"
},
"s0-l12": {
"url": "audio/s0-l12.m4a",
"voice": "am_fenrir",
"h": "994a6a59dca3"
},
"s0-l13": {
"url": "audio/s0-l13.m4a",
"voice": "am_michael",
"h": "6180c9c54212"
},
"s1-l0": {
"url": "audio/s1-l0.m4a",
"voice": "am_fenrir",
"h": "b88081ba25aa"
},
"s1-l1": {
"url": "audio/s1-l1.m4a",
"voice": "am_michael",
"h": "befae784695e"
},
"s1-l2": {
"url": "audio/s1-l2.m4a",
"voice": "am_fenrir",
"h": "5908f51f2272"
},
"s1-l3": {
"url": "audio/s1-l3.m4a",
"voice": "am_michael",
"h": "29f8753cce6f"
},
"s1-l4": {
"url": "audio/s1-l4.m4a",
"voice": "am_fenrir",
"h": "69511972b598"
},
"s1-l5": {
"url": "audio/s1-l5.m4a",
"voice": "am_michael",
"h": "40f1be236e61"
},
"s1-l6": {
"url": "audio/s1-l6.m4a",
"voice": "am_fenrir",
"h": "7feb2372dee0"
},
"s1-l7": {
"url": "audio/s1-l7.m4a",
"voice": "am_michael",
"h": "4e5886a7d523"
},
"s1-l8": {
"url": "audio/s1-l8.m4a",
"voice": "am_fenrir",
"h": "4acec0df7bf3"
},
"s1-l9": {
"url": "audio/s1-l9.m4a",
"voice": "am_michael",
"h": "02be08436099"
},
"s2-l2": {
"url": "audio/s2-l2.m4a",
"voice": "am_michael",
"h": "481e8dc2ff87"
},
"s2-l3": {
"url": "audio/s2-l3.m4a",
"voice": "am_michael",
"h": "3d615415e9d7"
},
"s2-l4": {
"url": "audio/s2-l4.m4a",
"voice": "am_michael",
"h": "0f71cd2bd9a4"
},
"s2-l5": {
"url": "audio/s2-l5.m4a",
"voice": "af_nicole",
"h": "38a15039977c"
},
"s2-l6": {
"url": "audio/s2-l6.m4a",
"voice": "am_michael",
"h": "e3f6df7ecc68"
},
"s2-l7": {
"url": "audio/s2-l7.m4a",
"voice": "af_nicole",
"h": "66d3449444d4"
},
"s2-l8": {
"url": "audio/s2-l8.m4a",
"voice": "am_michael",
"h": "9e89c4941c22"
},
"s3-l1": {
"url": "audio/s3-l1.m4a",
"voice": "am_michael",
"h": "ca90a2396b67"
},
"s3-l2": {
"url": "audio/s3-l2.m4a",
"voice": "am_michael",
"h": "36ed07142866"
},
"s3-l5": {
"url": "audio/s3-l5.m4a",
"voice": "am_michael",
"h": "de33064018c3"
},
"s3-l6": {
"url": "audio/s3-l6.m4a",
"voice": "am_michael",
"h": "205f92efd0fe"
},
"s3-l7": {
"url": "audio/s3-l7.m4a",
"voice": "am_michael",
"h": "b9ac7ef1cf80"
},
"s3-l8": {
"url": "audio/s3-l8.m4a",
"voice": "bf_emma",
"h": "f7bec2041388"
},
"s3-l9": {
"url": "audio/s3-l9.m4a",
"voice": "am_michael",
"h": "e9bd1a04d06d"
},
"s4-l0": {
"url": "audio/s4-l0.m4a",
"voice": "am_fenrir",
"h": "c4f1a680c7a0"
},
"s4-l1": {
"url": "audio/s4-l1.m4a",
"voice": "am_michael",
"h": "081f569abaa9"
},
"s4-l2": {
"url": "audio/s4-l2.m4a",
"voice": "am_michael",
"h": "3c6531fd00e5"
},
"s4-l3": {
"url": "audio/s4-l3.m4a",
"voice": "am_michael",
"h": "8e55326dc05d"
},
"s4-l4": {
"url": "audio/s4-l4.m4a",
"voice": "am_michael",
"h": "daaa1ce1d695"
},
"s4-l5": {
"url": "audio/s4-l5.m4a",
"voice": "am_michael",
"h": "05ca5f3ca5ea"
},
"s4-l6": {
"url": "audio/s4-l6.m4a",
"voice": "am_fenrir",
"h": "25c8b763cfdd"
},
"s4-l7": {
"url": "audio/s4-l7.m4a",
"voice": "am_michael",
"h": "a2c3aad191be"
},
"s5-l0": {
"url": "audio/s5-l0.m4a",
"voice": "am_michael",
"h": "43f9976584b8"
},
"s5-l1": {
"url": "audio/s5-l1.m4a",
"voice": "am_fenrir",
"h": "13e70d889657"
},
"s5-l2": {
"url": "audio/s5-l2.m4a",
"voice": "am_michael",
"h": "8ae85b128ec6"
},
"s5-l3": {
"url": "audio/s5-l3.m4a",
"voice": "am_fenrir",
"h": "1996d54ee0e1"
},
"s5-l4": {
"url": "audio/s5-l4.m4a",
"voice": "am_michael",
"h": "6e5d347f9dc6"
},
"s5-l5": {
"url": "audio/s5-l5.m4a",
"voice": "am_fenrir",
"h": "ed2463528734"
},
"s5-l6": {
"url": "audio/s5-l6.m4a",
"voice": "am_michael",
"h": "e1b6df6c1565"
},
"s5-l7": {
"url": "audio/s5-l7.m4a",
"voice": "am_fenrir",
"h": "c3453fec48de"
},
"s5-l8": {
"url": "audio/s5-l8.m4a",
"voice": "am_michael",
"h": "ace040d59f61"
},
"s5-l9": {
"url": "audio/s5-l9.m4a",
"voice": "am_fenrir",
"h": "85e0e4589367"
},
"s5-l10": {
"url": "audio/s5-l10.m4a",
"voice": "am_michael",
"h": "d41bd8ebb0d8"
},
"s6-l0": {
"url": "audio/s6-l0.m4a",
"voice": "am_fenrir",
"h": "8d5247e78f11"
},
"s6-l1": {
"url": "audio/s6-l1.m4a",
"voice": "am_michael",
"h": "517f69d14a97"
},
"s6-l2": {
"url": "audio/s6-l2.m4a",
"voice": "am_fenrir",
"h": "2f08ce013fad"
},
"s6-l3": {
"url": "audio/s6-l3.m4a",
"voice": "am_michael",
"h": "c95474ace245"
},
"s6-l4": {
"url": "audio/s6-l4.m4a",
"voice": "am_fenrir",
"h": "ea0118ed0d17"
},
"s6-l5": {
"url": "audio/s6-l5.m4a",
"voice": "am_michael",
"h": "6cac3e2cc0d4"
},
"s6-l6": {
"url": "audio/s6-l6.m4a",
"voice": "am_fenrir",
"h": "a1e871eb10b1"
},
"s6-l7": {
"url": "audio/s6-l7.m4a",
"voice": "am_michael",
"h": "659afeaee2bb"
},
"s6-l8": {
"url": "audio/s6-l8.m4a",
"voice": "am_fenrir",
"h": "b6daaed0a97a"
},
"s6-l9": {
"url": "audio/s6-l9.m4a",
"voice": "am_michael",
"h": "5b9b88fb91c8"
},
"s7-l0": {
"url": "audio/s7-l0.m4a",
"voice": "am_fenrir",
"h": "b416d619373f"
},
"s7-l2": {
"url": "audio/s7-l2.m4a",
"voice": "am_michael",
"h": "ae5176fa6d10"
},
"s7-l3": {
"url": "audio/s7-l3.m4a",
"voice": "am_michael",
"h": "c08e64e19524"
},
"s7-l4": {
"url": "audio/s7-l4.m4a",
"voice": "am_michael",
"h": "120e67f1609b"
},
"s7-l5": {
"url": "audio/s7-l5.m4a",
"voice": "af_bella",
"h": "187493d1e102"
},
"s7-l6": {
"url": "audio/s7-l6.m4a",
"voice": "am_michael",
"h": "3d3a03accad9"
},
"s7-l7": {
"url": "audio/s7-l7.m4a",
"voice": "am_fenrir",
"h": "f3c77d1952f1"
},
"s7-l8": {
"url": "audio/s7-l8.m4a",
"voice": "am_michael",
"h": "000f8857d5d7"
},
"s8-l0": {
"url": "audio/s8-l0.m4a",
"voice": "af_bella",
"h": "1b120cfaa5d4"
},
"s8-l1": {
"url": "audio/s8-l1.m4a",
"voice": "am_michael",
"h": "c92177a1c26d"
},
"s8-l2": {
"url": "audio/s8-l2.m4a",
"voice": "af_bella",
"h": "1f265d14e32e"
},
"s8-l3": {
"url": "audio/s8-l3.m4a",
"voice": "am_michael",
"h": "2a61d89053c9"
},
"s8-l4": {
"url": "audio/s8-l4.m4a",
"voice": "af_bella",
"h": "5384a06ce66e"
},
"s8-l5": {
"url": "audio/s8-l5.m4a",
"voice": "am_michael",
"h": "8316c5e7ad63"
},
"s8-l6": {
"url": "audio/s8-l6.m4a",
"voice": "af_bella",
"h": "dadf1340947d"
},
"s8-l7": {
"url": "audio/s8-l7.m4a",
"voice": "am_michael",
"h": "74b413ad338d"
},
"s8-l8": {
"url": "audio/s8-l8.m4a",
"voice": "af_bella",
"h": "8977c0eed2d8"
},
"s8-l9": {
"url": "audio/s8-l9.m4a",
"voice": "am_michael",
"h": "848e0ae908e5"
},
"s8-l11": {
"url": "audio/s8-l11.m4a",
"voice": "af_bella",
"h": "e7699227ad2e"
},
"s8-l12": {
"url": "audio/s8-l12.m4a",
"voice": "am_michael",
"h": "7c6e74c2ffe8"
},
"s9-l0": {
"url": "audio/s9-l0.m4a",
"voice": "am_fenrir",
"h": "7b93489f9b92"
},
"s9-l1": {
"url": "audio/s9-l1.m4a",
"voice": "am_michael",
"h": "ca1a9c0d9e8e"
},
"s9-l2": {
"url": "audio/s9-l2.m4a",
"voice": "am_michael",
"h": "c098a110eb4c"
},
"s9-l3": {
"url": "audio/s9-l3.m4a",
"voice": "am_fenrir",
"h": "649093a2f288"
},
"s9-l4": {
"url": "audio/s9-l4.m4a",
"voice": "am_michael",
"h": "84546e4e4d87"
},
"s9-l5": {
"url": "audio/s9-l5.m4a",
"voice": "am_fenrir",
"h": "887558fcc527"
},
"s9-l6": {
"url": "audio/s9-l6.m4a",
"voice": "am_michael",
"h": "ecea7c836462"
},
"s9-l7": {
"url": "audio/s9-l7.m4a",
"voice": "am_fenrir",
"h": "b64e37ca6d5e"
},
"s9-l8": {
"url": "audio/s9-l8.m4a",
"voice": "am_michael",
"h": "d560db1679de"
},
"s9-l9": {
"url": "audio/s9-l9.m4a",
"voice": "am_fenrir",
"h": "c972a7b82d85"
},
"s9-l10": {
"url": "audio/s9-l10.m4a",
"voice": "am_michael",
"h": "cf73a8dace89"
},
"s9-l11": {
"url": "audio/s9-l11.m4a",
"voice": "am_fenrir",
"h": "7d0b735e1c7a"
},
"s9-l12": {
"url": "audio/s9-l12.m4a",
"voice": "am_michael",
"h": "0e973d83336f"
},
"s10-l0": {
"url": "audio/s10-l0.m4a",
"voice": "af_bella",
"h": "d5458e25a9b6"
},
"s10-l1": {
"url": "audio/s10-l1.m4a",
"voice": "am_michael",
"h": "c972fe2727fd"
},
"s10-l2": {
"url": "audio/s10-l2.m4a",
"voice": "af_bella",
"h": "d78feaeda630"
},
"s10-l3": {
"url": "audio/s10-l3.m4a",
"voice": "am_michael",
"h": "fb8ff554cc58"
},
"s10-l4": {
"url": "audio/s10-l4.m4a",
"voice": "af_bella",
"h": "2c8c7c3401f7"
},
"s10-l5": {
"url": "audio/s10-l5.m4a",
"voice": "am_michael",
"h": "c19c95341924"
},
"s10-l6": {
"url": "audio/s10-l6.m4a",
"voice": "af_bella",
"h": "dddeef977a13"
},
"s10-l7": {
"url": "audio/s10-l7.m4a",
"voice": "am_michael",
"h": "b1ab6304356b"
},
"s10-l8": {
"url": "audio/s10-l8.m4a",
"voice": "af_bella",
"h": "5d48f625b8be"
},
"s10-l9": {
"url": "audio/s10-l9.m4a",
"voice": "am_michael",
"h": "1efcafab4717"
},
"s10-l10": {
"url": "audio/s10-l10.m4a",
"voice": "af_bella",
"h": "44aeba4f1b5c"
},
"s10-l11": {
"url": "audio/s10-l11.m4a",
"voice": "am_michael",
"h": "aa088e8e67e9"
},
"s11-l0": {
"url": "audio/s11-l0.m4a",
"voice": "am_michael",
"h": "5952aaecb4fd"
},
"s11-l1": {
"url": "audio/s11-l1.m4a",
"voice": "af_bella",
"h": "53c34bcd4808"
},
"s11-l3": {
"url": "audio/s11-l3.m4a",
"voice": "am_michael",
"h": "5ed0af090eba"
},
"s11-l4": {
"url": "audio/s11-l4.m4a",
"voice": "af_bella",
"h": "e6379106f6b2"
},
"s11-l5": {
"url": "audio/s11-l5.m4a",
"voice": "am_michael",
"h": "72d899b11975"
},
"s11-l6": {
"url": "audio/s11-l6.m4a",
"voice": "am_michael",
"h": "3bbdef261523"
},
"s11-l7": {
"url": "audio/s11-l7.m4a",
"voice": "af_bella",
"h": "5212e4017cbe"
},
"s11-l8": {
"url": "audio/s11-l8.m4a",
"voice": "am_michael",
"h": "7f3836818129"
},
"s12-l0": {
"url": "audio/s12-l0.m4a",
"voice": "am_fenrir",
"h": "bf9c638a33b4"
},
"s12-l1": {
"url": "audio/s12-l1.m4a",
"voice": "am_michael",
"h": "aa107f42d597"
},
"s12-l2": {
"url": "audio/s12-l2.m4a",
"voice": "am_michael",
"h": "e10bba86243d"
},
"s12-l3": {
"url": "audio/s12-l3.m4a",
"voice": "am_fenrir",
"h": "9623b304417c"
},
"s12-l4": {
"url": "audio/s12-l4.m4a",
"voice": "am_michael",
"h": "199d369ea702"
},
"s12-l5": {
"url": "audio/s12-l5.m4a",
"voice": "am_fenrir",
"h": "35ed2e63f247"
},
"s12-l6": {
"url": "audio/s12-l6.m4a",
"voice": "am_michael",
"h": "1b3254ae6df2"
},
"s12-l7": {
"url": "audio/s12-l7.m4a",
"voice": "am_fenrir",
"h": "7c1786d26791"
},
"s12-l8": {
"url": "audio/s12-l8.m4a",
"voice": "am_michael",
"h": "edfe544c7576"
},
"s13-l0": {
"url": "audio/s13-l0.m4a",
"voice": "am_michael",
"h": "8aac9aa55480"
},
"s13-l1": {
"url": "audio/s13-l1.m4a",
"voice": "af_bella",
"h": "5758d1d6c9a3"
},
"s13-l2": {
"url": "audio/s13-l2.m4a",
"voice": "am_michael",
"h": "14214cc5e9c1"
},
"s13-l3": {
"url": "audio/s13-l3.m4a",
"voice": "am_michael",
"h": "3a167ba568d0"
},
"s13-l4": {
"url": "audio/s13-l4.m4a",
"voice": "af_bella",
"h": "8e8b4e6bd378"
},
"s13-l5": {
"url": "audio/s13-l5.m4a",
"voice": "am_michael",
"h": "e32055a0abf5"
},
"s13-l6": {
"url": "audio/s13-l6.m4a",
"voice": "af_bella",
"h": "4d75775a16e4"
},
"s13-l7": {
"url": "audio/s13-l7.m4a",
"voice": "am_michael",
"h": "abc922d5450c"
},
"s13-l8": {
"url": "audio/s13-l8.m4a",
"voice": "af_bella",
"h": "854f1563dd2c"
},
"s13-l9": {
"url": "audio/s13-l9.m4a",
"voice": "am_michael",
"h": "69d32fd41584"
},
"s14-l0": {
"url": "audio/s14-l0.m4a",
"voice": "am_michael",
"h": "46f1cb21a7d3"
},
"s14-l1": {
"url": "audio/s14-l1.m4a",
"voice": "am_michael",
"h": "5ebba2c909e6"
},
"s14-l2": {
"url": "audio/s14-l2.m4a",
"voice": "am_fenrir",
"h": "d6569ee0af2b"
},
"s14-l3": {
"url": "audio/s14-l3.m4a",
"voice": "am_michael",
"h": "5a47be7d4007"
},
"s14-l4": {
"url": "audio/s14-l4.m4a",
"voice": "am_fenrir",
"h": "3ef37b7a56b2"
},
"s14-l5": {
"url": "audio/s14-l5.m4a",
"voice": "am_michael",
"h": "720e57c2ddfd"
},
"s14-l6": {
"url": "audio/s14-l6.m4a",
"voice": "am_michael",
"h": "77f300a67f09"
},
"s14-l7": {
"url": "audio/s14-l7.m4a",
"voice": "am_fenrir",
"h": "7b2fef3c845e"
},
"s14-l8": {
"url": "audio/s14-l8.m4a",
"voice": "am_michael",
"h": "708e1ccf29ab"
},
"s14-l9": {
"url": "audio/s14-l9.m4a",
"voice": "am_fenrir",
"h": "3329b261d6f4"
},
"s15-l0": {
"url": "audio/s15-l0.m4a",
"voice": "af_bella",
"h": "03f416ca9df1"
},
"s15-l1": {
"url": "audio/s15-l1.m4a",
"voice": "am_fenrir",
"h": "c5ae479c18b4"
},
"s15-l2": {
"url": "audio/s15-l2.m4a",
"voice": "am_michael",
"h": "42fc83524338"
},
"s15-l3": {
"url": "audio/s15-l3.m4a",
"voice": "am_michael",
"h": "5e7717b9d570"
},
"s15-l4": {
"url": "audio/s15-l4.m4a",
"voice": "af_bella",
"h": "bcdef4841470"
},
"s15-l5": {
"url": "audio/s15-l5.m4a",
"voice": "am_fenrir",
"h": "37a4f6ff670f"
},
"s15-l6": {
"url": "audio/s15-l6.m4a",
"voice": "am_michael",
"h": "1be5a5fc3f99"
},
"s15-l7": {
"url": "audio/s15-l7.m4a",
"voice": "am_fenrir",
"h": "ef75a5953bb9"
},
"s15-l8": {
"url": "audio/s15-l8.m4a",
"voice": "am_michael",
"h": "e30fe368006b"
},
"s15-l9": {
"url": "audio/s15-l9.m4a",
"voice": "af_bella",
"h": "c72eac1b18c8"
},
"s15-l10": {
"url": "audio/s15-l10.m4a",
"voice": "am_michael",
"h": "b48edecc53e8"
},
"s16-l0": {
"url": "audio/s16-l0.m4a",
"voice": "am_fenrir",
"h": "ce3ae94060c6"
},
"s16-l1": {
"url": "audio/s16-l1.m4a",
"voice": "am_michael",
"h": "dc40af452845"
},
"s16-l2": {
"url": "audio/s16-l2.m4a",
"voice": "am_fenrir",
"h": "bef84bd50969"
},
"s16-l3": {
"url": "audio/s16-l3.m4a",
"voice": "am_michael",
"h": "1f25478addc3"
},
"s16-l4": {
"url": "audio/s16-l4.m4a",
"voice": "am_fenrir",
"h": "d82fdbe479e9"
},
"s16-l5": {
"url": "audio/s16-l5.m4a",
"voice": "am_michael",
"h": "9caf754c1613"
},
"s16-l6": {
"url": "audio/s16-l6.m4a",
"voice": "am_fenrir",
"h": "e68f38f362b5"
},
"s16-l7": {
"url": "audio/s16-l7.m4a",
"voice": "am_michael",
"h": "9970a4a7a487"
},
"s17-l0": {
"url": "audio/s17-l0.m4a",
"voice": "af_bella",
"h": "8ece501285e0"
},
"s17-l1": {
"url": "audio/s17-l1.m4a",
"voice": "am_michael",
"h": "738e8e7b4f7b"
},
"s17-l2": {
"url": "audio/s17-l2.m4a",
"voice": "af_bella",
"h": "ee7a8c89032e"
},
"s17-l3": {
"url": "audio/s17-l3.m4a",
"voice": "am_michael",
"h": "0ea06b36a78a"
},
"s17-l4": {
"url": "audio/s17-l4.m4a",
"voice": "af_bella",
"h": "aec1513e0b79"
},
"s17-l5": {
"url": "audio/s17-l5.m4a",
"voice": "am_michael",
"h": "120e4a194254"
},
"s17-l6": {
"url": "audio/s17-l6.m4a",
"voice": "af_bella",
"h": "4bc2acec453b"
},
"s17-l7": {
"url": "audio/s17-l7.m4a",
"voice": "am_michael",
"h": "b401b623b53f"
},
"s18-l1": {
"url": "audio/s18-l1.m4a",
"voice": "am_fenrir",
"h": "0e839e867c25"
},
"s18-l2": {
"url": "audio/s18-l2.m4a",
"voice": "am_michael",
"h": "13a6821e2615"
},
"s18-l3": {
"url": "audio/s18-l3.m4a",
"voice": "am_michael",
"h": "4b89b3825dc8"
},
"s18-l4": {
"url": "audio/s18-l4.m4a",
"voice": "am_fenrir",
"h": "14f38c1cc9f3"
},
"s18-l5": {
"url": "audio/s18-l5.m4a",
"voice": "am_michael",
"h": "f837367f33f0"
},
"s18-l6": {
"url": "audio/s18-l6.m4a",
"voice": "am_fenrir",
"h": "cd26dd46fb79"
},
"s18-l7": {
"url": "audio/s18-l7.m4a",
"voice": "am_michael",
"h": "e91d589b4ec1"
},
"s19-l0": {
"url": "audio/s19-l0.m4a",
"voice": "am_michael",
"h": "2be497cb96e6"
},
"s19-l1": {
"url": "audio/s19-l1.m4a",
"voice": "am_michael",
"h": "de59f21b31cf"
},
"s19-l3": {
"url": "audio/s19-l3.m4a",
"voice": "am_michael",
"h": "c9862d971755"
},
"s19-l4": {
"url": "audio/s19-l4.m4a",
"voice": "af_bella",
"h": "ad757cb1c83b"
},
"s19-l5": {
"url": "audio/s19-l5.m4a",
"voice": "am_michael",
"h": "cd76885a5a79"
},
"s19-l6": {
"url": "audio/s19-l6.m4a",
"voice": "af_bella",
"h": "c052aae683b4"
},
"s19-l7": {
"url": "audio/s19-l7.m4a",
"voice": "am_michael",
"h": "c21f7e31ac96"
},
"s19-l8": {
"url": "audio/s19-l8.m4a",
"voice": "af_bella",
"h": "08b09e62c989"
},
"s19-l9": {
"url": "audio/s19-l9.m4a",
"voice": "am_michael",
"h": "71b92c409e52"
},
"s20-l0": {
"url": "audio/s20-l0.m4a",
"voice": "am_michael",
"h": "e9e2229ad8b3"
},
"s20-l1": {
"url": "audio/s20-l1.m4a",
"voice": "af_bella",
"h": "be8ca1ce3d30"
},
"s20-l2": {
"url": "audio/s20-l2.m4a",
"voice": "am_michael",
"h": "34d42d12d7ad"
},
"s20-l3": {
"url": "audio/s20-l3.m4a",
"voice": "af_bella",
"h": "ef18ba07e00e"
},
"s20-l5": {
"url": "audio/s20-l5.m4a",
"voice": "af_bella",
"h": "a9c43363105f"
},
"s20-l6": {
"url": "audio/s20-l6.m4a",
"voice": "am_michael",
"h": "d79067b8f3d1"
},
"s20-l7": {
"url": "audio/s20-l7.m4a",
"voice": "af_bella",
"h": "15e7b0293e7c"
},
"s20-l8": {
"url": "audio/s20-l8.m4a",
"voice": "am_michael",
"h": "99841dd2d770"
},
"s21-l0": {
"url": "audio/s21-l0.m4a",
"voice": "am_michael",
"h": "e165ca9f477d"
},
"s21-l1": {
"url": "audio/s21-l1.m4a",
"voice": "af_bella",
"h": "fcca201521f2"
},
"s21-l2": {
"url": "audio/s21-l2.m4a",
"voice": "am_michael",
"h": "1e42b3fdff67"
},
"s21-l3": {
"url": "audio/s21-l3.m4a",
"voice": "af_bella",
"h": "638fc8957cb7"
},
"s21-l4": {
"url": "audio/s21-l4.m4a",
"voice": "am_michael",
"h": "96109217299e"
},
"s21-l5": {
"url": "audio/s21-l5.m4a",
"voice": "af_bella",
"h": "5b83aef5e26b"
},
"s21-l6": {
"url": "audio/s21-l6.m4a",
"voice": "am_michael",
"h": "c7205eba6e83"
},
"s22-l0": {
"url": "audio/s22-l0.m4a",
"voice": "am_michael",
"h": "8588a28cfeb5"
},
"s22-l1": {
"url": "audio/s22-l1.m4a",
"voice": "am_fenrir",
"h": "8fb6078209b5"
},
"s22-l2": {
"url": "audio/s22-l2.m4a",
"voice": "am_michael",
"h": "3033d4c0b6b8"
},
"s22-l3": {
"url": "audio/s22-l3.m4a",
"voice": "af_bella",
"h": "4cca50f87f4a"
},
"s22-l4": {
"url": "audio/s22-l4.m4a",
"voice": "am_fenrir",
"h": "d3a40b72b2fe"
},
"s22-l5": {
"url": "audio/s22-l5.m4a",
"voice": "am_michael",
"h": "ae5ad3edbe71"
},
"s22-l6": {
"url": "audio/s22-l6.m4a",
"voice": "af_bella",
"h": "312e0b218297"
},
"s22-l7": {
"url": "audio/s22-l7.m4a",
"voice": "am_michael",
"h": "64e0a403f749"
},
"s23-l0": {
"url": "audio/s23-l0.m4a",
"voice": "am_michael",
"h": "4c96fdbb215d"
},
"s23-l1": {
"url": "audio/s23-l1.m4a",
"voice": "am_fenrir",
"h": "20c10f87a82c"
},
"s23-l2": {
"url": "audio/s23-l2.m4a",
"voice": "am_michael",
"h": "ffed8d63c808"
},
"s23-l3": {
"url": "audio/s23-l3.m4a",
"voice": "am_michael",
"h": "bbb437ac71ff"
},
"s23-l4": {
"url": "audio/s23-l4.m4a",
"voice": "am_michael",
"h": "9fdf7ef96ea0"
},
"s23-l5": {
"url": "audio/s23-l5.m4a",
"voice": "am_fenrir",
"h": "37e5b9b3aee6"
},
"s23-l6": {
"url": "audio/s23-l6.m4a",
"voice": "am_michael",
"h": "1ca4cb966ffe"
},
"s24-l0": {
"url": "audio/s24-l0.m4a",
"voice": "am_fenrir",
"h": "477e572abb2e"
},
"s24-l1": {
"url": "audio/s24-l1.m4a",
"voice": "am_michael",
"h": "191fa191dd8c"
},
"s24-l2": {
"url": "audio/s24-l2.m4a",
"voice": "am_michael",
"h": "15c4be3c30e3"
},
"s24-l3": {
"url": "audio/s24-l3.m4a",
"voice": "am_fenrir",
"h": "3168b6f4d9c2"
},
"s24-l4": {
"url": "audio/s24-l4.m4a",
"voice": "am_michael",
"h": "d6eacac4a0ee"
},
"s24-l5": {
"url": "audio/s24-l5.m4a",
"voice": "am_michael",
"h": "34663c459bce"
},
"s25-l0": {
"url": "audio/s25-l0.m4a",
"voice": "af_bella",
"h": "1f764bd235e4"
},
"s25-l1": {
"url": "audio/s25-l1.m4a",
"voice": "am_michael",
"h": "48a5b0293338"
},
"s25-l2": {
"url": "audio/s25-l2.m4a",
"voice": "af_bella",
"h": "2c1b89d8a106"
},
"s25-l3": {
"url": "audio/s25-l3.m4a",
"voice": "am_michael",
"h": "1f0d642b6731"
},
"s25-l4": {
"url": "audio/s25-l4.m4a",
"voice": "af_bella",
"h": "58941f4e0d86"
},
"s25-l5": {
"url": "audio/s25-l5.m4a",
"voice": "am_michael",
"h": "37897e7e30b0"
},
"r3-0-0": {
"url": "audio/r3-0-0.m4a",
"voice": "am_fenrir",
"h": "b29029e51d48"
},
"r3-0-1": {
"url": "audio/r3-0-1.m4a",
"voice": "am_fenrir",
"h": "c9e234b1d0b8"
},
"r3-1-0": {
"url": "audio/r3-1-0.m4a",
"voice": "am_fenrir",
"h": "9328876145a5"
},
"r3-1-1": {
"url": "audio/r3-1-1.m4a",
"voice": "am_fenrir",
"h": "57ac1bc97fa2"
},
"r3-2-0": {
"url": "audio/r3-2-0.m4a",
"voice": "af_nicole",
"h": "6635f7626452"
},
"r3-2-1": {
"url": "audio/r3-2-1.m4a",
"voice": "af_nicole",
"h": "eff8fc2e0441"
},
"r3-3-0": {
"url": "audio/r3-3-0.m4a",
"voice": "af_heart",
"h": "707708e181d5"
},
"r3-3-1": {
"url": "audio/r3-3-1.m4a",
"voice": "af_heart",
"h": "1368e9b7f7dc"
},
"r3-4-0": {
"url": "audio/r3-4-0.m4a",
"voice": "am_fenrir",
"h": "9e82c1695fb4"
},
"r3-4-1": {
"url": "audio/r3-4-1.m4a",
"voice": "am_fenrir",
"h": "feb218092a43"
},
"r3-5-0": {
"url": "audio/r3-5-0.m4a",
"voice": "am_fenrir",
"h": "691563ffbbc9"
},
"r3-5-1": {
"url": "audio/r3-5-1.m4a",
"voice": "am_fenrir",
"h": "6ed01d491de2"
},
"r3-6-0": {
"url": "audio/r3-6-0.m4a",
"voice": "am_fenrir",
"h": "588e320ff1b3"
},
"r3-6-1": {
"url": "audio/r3-6-1.m4a",
"voice": "am_fenrir",
"h": "b79aff14413e"
},
"r3-7-0": {
"url": "audio/r3-7-0.m4a",
"voice": "af_heart",
"h": "d9136bc4b914"
},
"r3-7-1": {
"url": "audio/r3-7-1.m4a",
"voice": "am_fenrir",
"h": "dbbedf26a9cd"
},
"r3-8-0": {
"url": "audio/r3-8-0.m4a",
"voice": "af_bella",
"h": "18b67825e3cd"
},
"r3-8-1": {
"url": "audio/r3-8-1.m4a",
"voice": "af_bella",
"h": "ee3f2a7cb5e8"
},
"r3-9-0": {
"url": "audio/r3-9-0.m4a",
"voice": "am_fenrir",
"h": "d1c2fcb764d7"
},
"r3-9-1": {
"url": "audio/r3-9-1.m4a",
"voice": "am_fenrir",
"h": "ab396535b6d9"
},
"r3-10-0": {
"url": "audio/r3-10-0.m4a",
"voice": "af_bella",
"h": "f482806dac3b"
},
"r3-10-1": {
"url": "audio/r3-10-1.m4a",
"voice": "af_bella",
"h": "c28ecd015bd3"
},
"r3-11-0": {
"url": "audio/r3-11-0.m4a",
"voice": "af_bella",
"h": "a1611137a3cd"
},
"r3-11-1": {
"url": "audio/r3-11-1.m4a",
"voice": "af_bella",
"h": "b8dab10691c8"
},
"r3-12-0": {
"url": "audio/r3-12-0.m4a",
"voice": "am_fenrir",
"h": "3e726c3d495b"
},
"r3-12-1": {
"url": "audio/r3-12-1.m4a",
"voice": "am_fenrir",
"h": "409da5c8afb7"
},
"r3-13-0": {
"url": "audio/r3-13-0.m4a",
"voice": "af_heart",
"h": "34739e2ee730"
},
"r3-13-1": {
"url": "audio/r3-13-1.m4a",
"voice": "af_bella",
"h": "ee1b902b4bdb"
},
"r3-14-0": {
"url": "audio/r3-14-0.m4a",
"voice": "af_heart",
"h": "5467037d8326"
},
"r3-14-1": {
"url": "audio/r3-14-1.m4a",
"voice": "am_fenrir",
"h": "9b098fccce8d"
},
"r3-15-0": {
"url": "audio/r3-15-0.m4a",
"voice": "af_heart",
"h": "50d8e747eaed"
},
"r3-15-1": {
"url": "audio/r3-15-1.m4a",
"voice": "af_bella",
"h": "74e6cf7b24c7"
},
"r3-16-0": {
"url": "audio/r3-16-0.m4a",
"voice": "am_fenrir",
"h": "a266476605bd"
},
"r3-16-1": {
"url": "audio/r3-16-1.m4a",
"voice": "af_heart",
"h": "edbb0744ce20"
},
"r3-17-0": {
"url": "audio/r3-17-0.m4a",
"voice": "af_bella",
"h": "139e93ddf924"
},
"r3-17-1": {
"url": "audio/r3-17-1.m4a",
"voice": "af_bella",
"h": "9477955fe31f"
},
"r3-18-0": {
"url": "audio/r3-18-0.m4a",
"voice": "af_heart",
"h": "906f8f7e3cb8"
},
"r3-18-1": {
"url": "audio/r3-18-1.m4a",
"voice": "af_heart",
"h": "81f4e06d9252"
},
"r3-19-0": {
"url": "audio/r3-19-0.m4a",
"voice": "af_heart",
"h": "43dc2f08319d"
},
"r3-19-1": {
"url": "audio/r3-19-1.m4a",
"voice": "af_heart",
"h": "a3965d1c1180"
},
"r3-20-0": {
"url": "audio/r3-20-0.m4a",
"voice": "af_bella",
"h": "b9605186d511"
},
"r3-20-1": {
"url": "audio/r3-20-1.m4a",
"voice": "af_heart",
"h": "4d161eb00f0f"
},
"r3-21-0": {
"url": "audio/r3-21-0.m4a",
"voice": "af_bella",
"h": "a5d97bf58533"
},
"r3-21-1": {
"url": "audio/r3-21-1.m4a",
"voice": "af_heart",
"h": "35fe6732e16e"
},
"r3-22-0": {
"url": "audio/r3-22-0.m4a",
"voice": "am_fenrir",
"h": "88ee55bbfdb6"
},
"r3-22-1": {
"url": "audio/r3-22-1.m4a",
"voice": "af_heart",
"h": "a3f197a2ad4f"
},
"r3-23-0": {
"url": "audio/r3-23-0.m4a",
"voice": "am_fenrir",
"h": "1f5a3d31fff0"
},
"r3-23-1": {
"url": "audio/r3-23-1.m4a",
"voice": "af_heart",
"h": "d5bbbef30f6e"
},
"r3-24-0": {
"url": "audio/r3-24-0.m4a",
"voice": "am_fenrir",
"h": "aebfd16cd424"
},
"r3-24-1": {
"url": "audio/r3-24-1.m4a",
"voice": "am_fenrir",
"h": "37883cb5d14f"
},
"r3-25-0": {
"url": "audio/r3-25-0.m4a",
"voice": "af_bella",
"h": "641f508f7e6c"
},
"r3-25-1": {
"url": "audio/r3-25-1.m4a",
"voice": "af_heart",
"h": "4cb88b2b6651"
},
"l0-p0": {
"url": "audio/l0-p0.m4a",
"voice": "am_michael",
"h": "675d9d2530e6"
},
"l0-d": {
"url": "audio/l0-d.m4a",
"voice": "am_michael",
"h": "dc61c724b92c"
},
"l1-p0": {
"url": "audio/l1-p0.m4a",
"voice": "am_michael",
"h": "3c2afd46084e"
},
"l1-p1": {
"url": "audio/l1-p1.m4a",
"voice": "am_michael",
"h": "179633cc4519"
},
"l1-d": {
"url": "audio/l1-d.m4a",
"voice": "am_michael",
"h": "02ed7d20e5e9"
},
"l2-p0": {
"url": "audio/l2-p0.m4a",
"voice": "am_michael",
"h": "7809d3e2221a"
},
"l2-p1": {
"url": "audio/l2-p1.m4a",
"voice": "am_michael",
"h": "19771129d2d6"
},
"l2-d": {
"url": "audio/l2-d.m4a",
"voice": "am_michael",
"h": "85572575c7ae"
},
"l3-p0": {
"url": "audio/l3-p0.m4a",
"voice": "am_michael",
"h": "4c18d35d7ca1"
},
"l3-p1": {
"url": "audio/l3-p1.m4a",
"voice": "am_michael",
"h": "527bce60a08e"
},
"l3-p2": {
"url": "audio/l3-p2.m4a",
"voice": "am_michael",
"h": "01cb954bf17a"
},
"l3-d": {
"url": "audio/l3-d.m4a",
"voice": "am_michael",
"h": "487254f0854f"
},
"l4-d": {
"url": "audio/l4-d.m4a",
"voice": "am_michael",
"h": "2bee5450e3c8"
},
"l6-p0": {
"url": "audio/l6-p0.m4a",
"voice": "am_michael",
"h": "8600f77487ee"
},
"l6-p1": {
"url": "audio/l6-p1.m4a",
"voice": "am_michael",
"h": "0821811a9a8c"
},
"l6-p2": {
"url": "audio/l6-p2.m4a",
"voice": "am_michael",
"h": "c42035f81cce"
},
"l6-d": {
"url": "audio/l6-d.m4a",
"voice": "am_michael",
"h": "b0f7b1274201"
},
"l7-p0": {
"url": "audio/l7-p0.m4a",
"voice": "am_michael",
"h": "430342146b6b"
},
"l7-p1": {
"url": "audio/l7-p1.m4a",
"voice": "am_michael",
"h": "b60cce73343b"
},
"l8-p0": {
"url": "audio/l8-p0.m4a",
"voice": "am_michael",
"h": "37a74f0b1a6d"
},
"l8-p1": {
"url": "audio/l8-p1.m4a",
"voice": "am_michael",
"h": "0b769428dbdb"
},
"l8-d": {
"url": "audio/l8-d.m4a",
"voice": "am_michael",
"h": "4d8a668fa0b7"
},
"l9-p0": {
"url": "audio/l9-p0.m4a",
"voice": "am_michael",
"h": "5862f37cdb14"
},
"l9-p1": {
"url": "audio/l9-p1.m4a",
"voice": "am_michael",
"h": "78e7aef01ead"
},
"l9-d": {
"url": "audio/l9-d.m4a",
"voice": "am_michael",
"h": "cee877e5055a"
},
"l10-p0": {
"url": "audio/l10-p0.m4a",
"voice": "am_michael",
"h": "618d5d8883d9"
},
"l10-p1": {
"url": "audio/l10-p1.m4a",
"voice": "am_michael",
"h": "7c28e5c358a7"
},
"l10-d": {
"url": "audio/l10-d.m4a",
"voice": "am_michael",
"h": "a755e6be7ce8"
},
"l11-p1": {
"url": "audio/l11-p1.m4a",
"voice": "am_michael",
"h": "e84382f180ef"
},
"l11-d": {
"url": "audio/l11-d.m4a",
"voice": "am_michael",
"h": "bfcbdb135d49"
},
"l12-p1": {
"url": "audio/l12-p1.m4a",
"voice": "am_michael",
"h": "d3145664c490"
},
"l12-d": {
"url": "audio/l12-d.m4a",
"voice": "am_michael",
"h": "676512460b23"
},
"l13-p0": {
"url": "audio/l13-p0.m4a",
"voice": "am_michael",
"h": "f877371927ee"
},
"l13-p1": {
"url": "audio/l13-p1.m4a",
"voice": "am_michael",
"h": "6cdedff1f06d"
},
"l13-d": {
"url": "audio/l13-d.m4a",
"voice": "am_michael",
"h": "6661b32490dc"
},
"l14-p0": {
"url": "audio/l14-p0.m4a",
"voice": "am_michael",
"h": "d0f0d3da3e8d"
},
"l14-p1": {
"url": "audio/l14-p1.m4a",
"voice": "am_michael",
"h": "0c2e9a2ba979"
},
"l14-p2": {
"url": "audio/l14-p2.m4a",
"voice": "am_michael",
"h": "b196fd47ddc1"
},
"l14-d": {
"url": "audio/l14-d.m4a",
"voice": "am_michael",
"h": "d0f0d3da3e8d"
},
"l15-p0": {
"url": "audio/l15-p0.m4a",
"voice": "am_michael",
"h": "e1e9d477c3c7"
},
"l15-p2": {
"url": "audio/l15-p2.m4a",
"voice": "am_michael",
"h": "ec73a897c86c"
},
"l15-d": {
"url": "audio/l15-d.m4a",
"voice": "am_michael",
"h": "f08c1958a3eb"
},
"l16-p0": {
"url": "audio/l16-p0.m4a",
"voice": "am_michael",
"h": "571c99cab6e8"
},
"l16-p1": {
"url": "audio/l16-p1.m4a",
"voice": "am_michael",
"h": "7aed2e7739f3"
},
"l16-d": {
"url": "audio/l16-d.m4a",
"voice": "am_michael",
"h": "fb5bbf96c16a"
},
"l17-p0": {
"url": "audio/l17-p0.m4a",
"voice": "am_michael",
"h": "83c1ba8593a0"
},
"l17-p1": {
"url": "audio/l17-p1.m4a",
"voice": "am_michael",
"h": "fc810a659245"
},
"l17-d": {
"url": "audio/l17-d.m4a",
"voice": "am_michael",
"h": "4ae8a4e2f1b1"
},
"l18-p0": {
"url": "audio/l18-p0.m4a",
"voice": "am_michael",
"h": "18c23eafbce7"
},
"l18-p1": {
"url": "audio/l18-p1.m4a",
"voice": "am_michael",
"h": "6e120aa94573"
},
"l18-d": {
"url": "audio/l18-d.m4a",
"voice": "am_michael",
"h": "3c12bfc55dc0"
},
"l19-p0": {
"url": "audio/l19-p0.m4a",
"voice": "am_michael",
"h": "2c2e956aacef"
},
"l19-p1": {
"url": "audio/l19-p1.m4a",
"voice": "am_michael",
"h": "f1da7a7c2322"
},
"l19-d": {
"url": "audio/l19-d.m4a",
"voice": "am_michael",
"h": "20261ab365b7"
},
"l20-p0": {
"url": "audio/l20-p0.m4a",
"voice": "am_michael",
"h": "2724dbd742de"
},
"l20-p1": {
"url": "audio/l20-p1.m4a",
"voice": "am_michael",
"h": "f4630629f78f"
},
"l20-d": {
"url": "audio/l20-d.m4a",
"voice": "am_michael",
"h": "e2034694b9be"
},
"l21-p0": {
"url": "audio/l21-p0.m4a",
"voice": "am_michael",
"h": "8a48b2d50bae"
},
"l21-p1": {
"url": "audio/l21-p1.m4a",
"voice": "am_michael",
"h": "8b8fdafae39e"
},
"l21-d": {
"url": "audio/l21-d.m4a",
"voice": "am_michael",
"h": "f8325f41d3a6"
},
"l22-p0": {
"url": "audio/l22-p0.m4a",
"voice": "am_michael",
"h": "955b97052d5e"
},
"l22-p1": {
"url": "audio/l22-p1.m4a",
"voice": "am_michael",
"h": "de72984b96df"
},
"l22-d": {
"url": "audio/l22-d.m4a",
"voice": "am_michael",
"h": "fa322302bfeb"
},
"qz0-a": {
"url": "audio/qz0-a.m4a",
"voice": "am_michael",
"h": "e47c0a687af8"
},
"qz0-b": {
"url": "audio/qz0-b.m4a",
"voice": "am_michael",
"h": "675d9d2530e6"
},
"qz1-a": {
"url": "audio/qz1-a.m4a",
"voice": "am_michael",
"h": "ad59e99abf7d"
},
"qz1-b": {
"url": "audio/qz1-b.m4a",
"voice": "am_michael",
"h": "3c2afd46084e"
},
"qz2-a": {
"url": "audio/qz2-a.m4a",
"voice": "am_michael",
"h": "c0da6ea18a61"
},
"qz2-b": {
"url": "audio/qz2-b.m4a",
"voice": "am_michael",
"h": "7809d3e2221a"
},
"qz3-a": {
"url": "audio/qz3-a.m4a",
"voice": "am_michael",
"h": "7478ffb3dc3a"
},
"qz3-b": {
"url": "audio/qz3-b.m4a",
"voice": "am_michael",
"h": "4c18d35d7ca1"
},
"qz4-a": {
"url": "audio/qz4-a.m4a",
"voice": "af_heart",
"h": "acb99178d8f1"
},
"qz4-b": {
"url": "audio/qz4-b.m4a",
"voice": "af_heart",
"h": "02259c88feaa"
},
"qz6-a": {
"url": "audio/qz6-a.m4a",
"voice": "am_michael",
"h": "77a6720e2eeb"
},
"qz6-b": {
"url": "audio/qz6-b.m4a",
"voice": "am_michael",
"h": "8600f77487ee"
},
"qz7-a": {
"url": "audio/qz7-a.m4a",
"voice": "am_michael",
"h": "fd4c7ca74a57"
},
"qz7-b": {
"url": "audio/qz7-b.m4a",
"voice": "am_michael",
"h": "430342146b6b"
},
"qz8-a": {
"url": "audio/qz8-a.m4a",
"voice": "am_michael",
"h": "8ec315b3fa85"
},
"qz8-b": {
"url": "audio/qz8-b.m4a",
"voice": "am_michael",
"h": "37a74f0b1a6d"
},
"qz9-a": {
"url": "audio/qz9-a.m4a",
"voice": "am_michael",
"h": "31cc252bb5bf"
},
"qz9-b": {
"url": "audio/qz9-b.m4a",
"voice": "am_michael",
"h": "5862f37cdb14"
},
"qz10-a": {
"url": "audio/qz10-a.m4a",
"voice": "am_michael",
"h": "8c0a2c03e72c"
},
"qz10-b": {
"url": "audio/qz10-b.m4a",
"voice": "am_michael",
"h": "618d5d8883d9"
},
"qz11-a": {
"url": "audio/qz11-a.m4a",
"voice": "af_heart",
"h": "6eb94dc251eb"
},
"qz11-b": {
"url": "audio/qz11-b.m4a",
"voice": "am_michael",
"h": "0cb3ee8967b9"
},
"qz12-a": {
"url": "audio/qz12-a.m4a",
"voice": "af_heart",
"h": "251ca471e2d7"
},
"qz12-b": {
"url": "audio/qz12-b.m4a",
"voice": "af_heart",
"h": "1b1a7cb0a377"
},
"qz13-a": {
"url": "audio/qz13-a.m4a",
"voice": "am_michael",
"h": "4bf1186995b7"
},
"qz13-b": {
"url": "audio/qz13-b.m4a",
"voice": "am_michael",
"h": "f877371927ee"
},
"qz14-a": {
"url": "audio/qz14-a.m4a",
"voice": "am_michael",
"h": "87333a977917"
},
"qz14-b": {
"url": "audio/qz14-b.m4a",
"voice": "am_michael",
"h": "d0f0d3da3e8d"
},
"qz15-a": {
"url": "audio/qz15-a.m4a",
"voice": "am_michael",
"h": "ac094b6fef56"
},
"qz15-b": {
"url": "audio/qz15-b.m4a",
"voice": "am_michael",
"h": "e1e9d477c3c7"
},
"qz16-a": {
"url": "audio/qz16-a.m4a",
"voice": "am_michael",
"h": "b228722025ad"
},
"qz16-b": {
"url": "audio/qz16-b.m4a",
"voice": "am_michael",
"h": "571c99cab6e8"
},
"qz17-a": {
"url": "audio/qz17-a.m4a",
"voice": "am_michael",
"h": "696505af144b"
},
"qz17-b": {
"url": "audio/qz17-b.m4a",
"voice": "am_michael",
"h": "83c1ba8593a0"
},
"qz18-a": {
"url": "audio/qz18-a.m4a",
"voice": "am_michael",
"h": "ebb9af3e4440"
},
"qz18-b": {
"url": "audio/qz18-b.m4a",
"voice": "am_michael",
"h": "18c23eafbce7"
},
"qz19-a": {
"url": "audio/qz19-a.m4a",
"voice": "am_michael",
"h": "19224c14c6e4"
},
"qz19-b": {
"url": "audio/qz19-b.m4a",
"voice": "am_michael",
"h": "2c2e956aacef"
},
"qz20-a": {
"url": "audio/qz20-a.m4a",
"voice": "am_michael",
"h": "01ea70291a7b"
},
"qz20-b": {
"url": "audio/qz20-b.m4a",
"voice": "am_michael",
"h": "2724dbd742de"
},
"qz21-a": {
"url": "audio/qz21-a.m4a",
"voice": "am_michael",
"h": "753da07bee93"
},
"qz21-b": {
"url": "audio/qz21-b.m4a",
"voice": "am_michael",
"h": "8a48b2d50bae"
},
"qz22-a": {
"url": "audio/qz22-a.m4a",
"voice": "am_michael",
"h": "0c389305ea77"
},
"qz22-b": {
"url": "audio/qz22-b.m4a",
"voice": "am_michael",
"h": "955b97052d5e"
},
"qz0-0-o0": {
"url": "audio/qz0-0-o0.m4a",
"voice": "af_heart",
"h": "390291c73e53"
},
"qz0-0-o1": {
"url": "audio/qz0-0-o1.m4a",
"voice": "af_heart",
"h": "d2168d3d4a44"
},
"qz0-0-o2": {
"url": "audio/qz0-0-o2.m4a",
"voice": "af_heart",
"h": "6767133a5c36"
},
"qz1-0-t": {
"url": "audio/qz1-0-t.m4a",
"voice": "am_michael",
"h": "98b923f40bd1"
},
"qz1-1-t": {
"url": "audio/qz1-1-t.m4a",
"voice": "am_michael",
"h": "d9c39db4fa81"
},
"qz2-0-t": {
"url": "audio/qz2-0-t.m4a",
"voice": "am_michael",
"h": "3fc326293021"
},
"qz2-1-o0": {
"url": "audio/qz2-1-o0.m4a",
"voice": "af_heart",
"h": "4d10ba899476"
},
"qz2-1-o1": {
"url": "audio/qz2-1-o1.m4a",
"voice": "af_heart",
"h": "800b5406506f"
},
"qz2-1-o2": {
"url": "audio/qz2-1-o2.m4a",
"voice": "af_heart",
"h": "25776826145d"
},
"qz3-0-t": {
"url": "audio/qz3-0-t.m4a",
"voice": "am_michael",
"h": "f573d8160a54"
},
"qz3-1-o0": {
"url": "audio/qz3-1-o0.m4a",
"voice": "af_heart",
"h": "fb4b43db365a"
},
"qz3-1-o1": {
"url": "audio/qz3-1-o1.m4a",
"voice": "af_heart",
"h": "221671b6019e"
},
"qz3-1-o2": {
"url": "audio/qz3-1-o2.m4a",
"voice": "af_heart",
"h": "ae82d5510939"
},
"qz4-0-o0": {
"url": "audio/qz4-0-o0.m4a",
"voice": "af_heart",
"h": "b86dc6e99ca4"
},
"qz4-0-o1": {
"url": "audio/qz4-0-o1.m4a",
"voice": "af_heart",
"h": "5c12577d888c"
},
"qz4-0-o2": {
"url": "audio/qz4-0-o2.m4a",
"voice": "af_heart",
"h": "485914348436"
},
"qz5-0-o0": {
"url": "audio/qz5-0-o0.m4a",
"voice": "af_heart",
"h": "3b3f285ad455"
},
"qz5-0-o1": {
"url": "audio/qz5-0-o1.m4a",
"voice": "af_heart",
"h": "1c81a18d8585"
},
"qz5-0-o2": {
"url": "audio/qz5-0-o2.m4a",
"voice": "af_heart",
"h": "0a0bc44616a8"
},
"qz6-0-t": {
"url": "audio/qz6-0-t.m4a",
"voice": "am_michael",
"h": "6df5524aa851"
},
"qz6-1-o0": {
"url": "audio/qz6-1-o0.m4a",
"voice": "af_heart",
"h": "9e28eecda0bb"
},
"qz6-1-o1": {
"url": "audio/qz6-1-o1.m4a",
"voice": "af_heart",
"h": "97d353fa2f2a"
},
"qz6-1-o2": {
"url": "audio/qz6-1-o2.m4a",
"voice": "af_heart",
"h": "0b1318bf21b0"
},
"qz7-0-o0": {
"url": "audio/qz7-0-o0.m4a",
"voice": "af_heart",
"h": "cd6a201c24cd"
},
"qz7-0-o1": {
"url": "audio/qz7-0-o1.m4a",
"voice": "af_heart",
"h": "cfa109f9efcb"
},
"qz7-0-o2": {
"url": "audio/qz7-0-o2.m4a",
"voice": "af_heart",
"h": "d1e12ecb0e83"
},
"qz8-0-t": {
"url": "audio/qz8-0-t.m4a",
"voice": "am_michael",
"h": "e708f0fb5d15"
},
"qz9-0-t": {
"url": "audio/qz9-0-t.m4a",
"voice": "am_michael",
"h": "31cc252bb5bf"
},
"qz9-1-o0": {
"url": "audio/qz9-1-o0.m4a",
"voice": "af_heart",
"h": "e1277b5c71ad"
},
"qz9-1-o1": {
"url": "audio/qz9-1-o1.m4a",
"voice": "af_heart",
"h": "4fe627273f4f"
},
"qz9-1-o2": {
"url": "audio/qz9-1-o2.m4a",
"voice": "af_heart",
"h": "c28bff9b45a0"
},
"qz10-0-o0": {
"url": "audio/qz10-0-o0.m4a",
"voice": "af_heart",
"h": "501e09246157"
},
"qz10-0-o1": {
"url": "audio/qz10-0-o1.m4a",
"voice": "af_heart",
"h": "e9f1634444cc"
},
"qz10-0-o2": {
"url": "audio/qz10-0-o2.m4a",
"voice": "af_heart",
"h": "c031efae3a9f"
},
"qz11-0-o0": {
"url": "audio/qz11-0-o0.m4a",
"voice": "af_heart",
"h": "037de6727d33"
},
"qz11-0-o1": {
"url": "audio/qz11-0-o1.m4a",
"voice": "af_heart",
"h": "6daf45b88f2a"
},
"qz11-0-o2": {
"url": "audio/qz11-0-o2.m4a",
"voice": "af_heart",
"h": "506fd4a56da4"
},
"qz12-0-o0": {
"url": "audio/qz12-0-o0.m4a",
"voice": "af_heart",
"h": "af63bed0febd"
},
"qz12-0-o1": {
"url": "audio/qz12-0-o1.m4a",
"voice": "af_heart",
"h": "d08db86a1bc2"
},
"qz12-0-o2": {
"url": "audio/qz12-0-o2.m4a",
"voice": "af_heart",
"h": "3c5c1bbfe199"
},
"qz13-0-t": {
"url": "audio/qz13-0-t.m4a",
"voice": "am_michael",
"h": "3ad39d388821"
},
"qz13-1-o0": {
"url": "audio/qz13-1-o0.m4a",
"voice": "af_heart",
"h": "c8c201349ecb"
},
"qz13-1-o1": {
"url": "audio/qz13-1-o1.m4a",
"voice": "af_heart",
"h": "d49e5a3d1343"
},
"qz13-1-o2": {
"url": "audio/qz13-1-o2.m4a",
"voice": "af_heart",
"h": "7c00f42ce522"
},
"qz14-0-o0": {
"url": "audio/qz14-0-o0.m4a",
"voice": "af_heart",
"h": "36976ee1ca59"
},
"qz14-0-o1": {
"url": "audio/qz14-0-o1.m4a",
"voice": "af_heart",
"h": "76918b048e13"
},
"qz14-0-o2": {
"url": "audio/qz14-0-o2.m4a",
"voice": "af_heart",
"h": "38e7f1cf35cf"
},
"qz14-1-t": {
"url": "audio/qz14-1-t.m4a",
"voice": "am_michael",
"h": "e8322b40d924"
},
"qz15-0-o0": {
"url": "audio/qz15-0-o0.m4a",
"voice": "af_heart",
"h": "db7bcb8f761b"
},
"qz15-0-o1": {
"url": "audio/qz15-0-o1.m4a",
"voice": "af_heart",
"h": "5011b185187d"
},
"qz15-0-o2": {
"url": "audio/qz15-0-o2.m4a",
"voice": "af_heart",
"h": "2435b20b05d7"
},
"qz16-0-o0": {
"url": "audio/qz16-0-o0.m4a",
"voice": "af_heart",
"h": "75168ba2be37"
},
"qz16-0-o1": {
"url": "audio/qz16-0-o1.m4a",
"voice": "af_heart",
"h": "144d9a7804cb"
},
"qz16-0-o2": {
"url": "audio/qz16-0-o2.m4a",
"voice": "af_heart",
"h": "7b0478a81aa0"
},
"qz17-0-t": {
"url": "audio/qz17-0-t.m4a",
"voice": "am_michael",
"h": "59a13f38ec8d"
},
"qz18-0-o0": {
"url": "audio/qz18-0-o0.m4a",
"voice": "af_heart",
"h": "9f3eb2cdf72e"
},
"qz18-0-o1": {
"url": "audio/qz18-0-o1.m4a",
"voice": "af_heart",
"h": "df1bf09e9790"
},
"qz18-0-o2": {
"url": "audio/qz18-0-o2.m4a",
"voice": "af_heart",
"h": "ba7babf48396"
},
"qz19-0-t": {
"url": "audio/qz19-0-t.m4a",
"voice": "am_michael",
"h": "c8dd2bf2d2d9"
},
"qz20-0-o0": {
"url": "audio/qz20-0-o0.m4a",
"voice": "af_heart",
"h": "244631271c29"
},
"qz20-0-o1": {
"url": "audio/qz20-0-o1.m4a",
"voice": "af_heart",
"h": "cc205cdf716a"
},
"qz20-0-o2": {
"url": "audio/qz20-0-o2.m4a",
"voice": "af_heart",
"h": "e843a3348790"
},
"qz21-0-o0": {
"url": "audio/qz21-0-o0.m4a",
"voice": "af_heart",
"h": "6dec448247b7"
},
"qz21-0-o1": {
"url": "audio/qz21-0-o1.m4a",
"voice": "af_heart",
"h": "c1ea4d799a6e"
},
"qz21-0-o2": {
"url": "audio/qz21-0-o2.m4a",
"voice": "af_heart",
"h": "d654f3e0ac9a"
},
"qz22-0-o0": {
"url": "audio/qz22-0-o0.m4a",
"voice": "af_heart",
"h": "45b00c0bd168"
},
"qz22-0-o1": {
"url": "audio/qz22-0-o1.m4a",
"voice": "af_heart",
"h": "67952693dc92"
},
"qz22-0-o2": {
"url": "audio/qz22-0-o2.m4a",
"voice": "af_heart",
"h": "293998a306cb"
},
"c-fx-r1": {
"url": "audio/c-fx-r1.m4a",
"voice": "af_heart",
"h": "a777faf2abf6"
},
"c-fx-r2": {
"url": "audio/c-fx-r2.m4a",
"voice": "af_heart",
"h": "48a04805cf14"
},
"c-fx-turn": {
"url": "audio/c-fx-turn.m4a",
"voice": "af_heart",
"h": "db11e2b73aec"
},
"c-fx-good": {
"url": "audio/c-fx-good.m4a",
"voice": "af_heart",
"h": "8d297b5b5f5f"
},
"c-fx-pace": {
"url": "audio/c-fx-pace.m4a",
"voice": "af_heart",
"h": "4400c922a044"
},
"c-fx-pause": {
"url": "audio/c-fx-pause.m4a",
"voice": "af_heart",
"h": "5a6eb0d13554"
},
"c-fx-end": {
"url": "audio/c-fx-end.m4a",
"voice": "af_heart",
"h": "6873ba63053a"
},
"c-fx-nospeech": {
"url": "audio/c-fx-nospeech.m4a",
"voice": "af_heart",
"h": "ed4805a844a6"
},
"c-fx-done1": {
"url": "audio/c-fx-done1.m4a",
"voice": "af_heart",
"h": "bf5ca2ebaeba"
},
"c-fx-done2": {
"url": "audio/c-fx-done2.m4a",
"voice": "af_heart",
"h": "a18b7da4ceb8"
},
"c-fx-quiz": {
"url": "audio/c-fx-quiz.m4a",
"voice": "af_heart",
"h": "1341b9a7dbe2"
},
"c-fx-right": {
"url": "audio/c-fx-right.m4a",
"voice": "af_heart",
"h": "b2628542e8aa"
},
"c-fx-wrong": {
"url": "audio/c-fx-wrong.m4a",
"voice": "af_heart",
"h": "73b9a8b843cc"
},
"c-fx-say": {
"url": "audio/c-fx-say.m4a",
"voice": "af_heart",
"h": "02c7d79a55f0"
},
"c-fx-ldone": {
"url": "audio/c-fx-ldone.m4a",
"voice": "af_heart",
"h": "e0e187096e6e"
},
"c-fx-breathe": {
"url": "audio/c-fx-breathe.m4a",
"voice": "af_heart",
"h": "8f3d302679cf"
},
"c-sc0-intro": {
"url": "audio/c-sc0-intro.m4a",
"voice": "af_heart",
"h": "c42e0dd6c172"
},
"c-s0-l1": {
"url": "audio/c-s0-l1.m4a",
"voice": "af_heart",
"h": "a946a76b5aa7"
},
"c-s0-l3": {
"url": "audio/c-s0-l3.m4a",
"voice": "af_heart",
"h": "7dbab00e6242"
},
"c-s0-l5": {
"url": "audio/c-s0-l5.m4a",
"voice": "af_heart",
"h": "e0e652a4080c"
},
"c-s0-l7": {
"url": "audio/c-s0-l7.m4a",
"voice": "af_heart",
"h": "dea761cde054"
},
"c-s0-l9": {
"url": "audio/c-s0-l9.m4a",
"voice": "af_heart",
"h": "e00ea6841ae8"
},
"c-s0-l11": {
"url": "audio/c-s0-l11.m4a",
"voice": "af_heart",
"h": "9a69472f7e9c"
},
"c-s0-l13": {
"url": "audio/c-s0-l13.m4a",
"voice": "af_heart",
"h": "902172e39aff"
},
"c-sc1-intro": {
"url": "audio/c-sc1-intro.m4a",
"voice": "af_heart",
"h": "81b7510cef72"
},
"c-s1-l1": {
"url": "audio/c-s1-l1.m4a",
"voice": "af_heart",
"h": "7c3344b5a3a2"
},
"c-s1-l3": {
"url": "audio/c-s1-l3.m4a",
"voice": "af_heart",
"h": "64f8354f500c"
},
"c-s1-l5": {
"url": "audio/c-s1-l5.m4a",
"voice": "af_heart",
"h": "95792ad40d00"
},
"c-s1-l7": {
"url": "audio/c-s1-l7.m4a",
"voice": "af_heart",
"h": "da2e30c25457"
},
"c-s1-l9": {
"url": "audio/c-s1-l9.m4a",
"voice": "af_heart",
"h": "61653943fd92"
},
"c-sc2-intro": {
"url": "audio/c-sc2-intro.m4a",
"voice": "af_heart",
"h": "0c75f17d3cf0"
},
"c-s2-l1": {
"url": "audio/c-s2-l1.m4a",
"voice": "af_heart",
"h": "ef77989ce0ab"
},
"c-s2-l2": {
"url": "audio/c-s2-l2.m4a",
"voice": "af_heart",
"h": "8a990a069923"
},
"c-s2-l3": {
"url": "audio/c-s2-l3.m4a",
"voice": "af_heart",
"h": "f43154c8579f"
},
"c-s2-l4": {
"url": "audio/c-s2-l4.m4a",
"voice": "af_heart",
"h": "505970e933ef"
},
"c-s2-l6": {
"url": "audio/c-s2-l6.m4a",
"voice": "af_heart",
"h": "927022b9eb84"
},
"c-s2-l8": {
"url": "audio/c-s2-l8.m4a",
"voice": "af_heart",
"h": "5ec855d423a8"
},
"c-sc3-intro": {
"url": "audio/c-sc3-intro.m4a",
"voice": "af_heart",
"h": "f20337b9ee43"
},
"c-s3-l1": {
"url": "audio/c-s3-l1.m4a",
"voice": "af_heart",
"h": "16a6461e64a7"
},
"c-s3-l2": {
"url": "audio/c-s3-l2.m4a",
"voice": "af_heart",
"h": "4132a6964a2e"
},
"c-s3-l3": {
"url": "audio/c-s3-l3.m4a",
"voice": "af_heart",
"h": "54138bb8a8e1"
},
"c-s3-l5": {
"url": "audio/c-s3-l5.m4a",
"voice": "af_heart",
"h": "535f50804a1d"
},
"c-s3-l6": {
"url": "audio/c-s3-l6.m4a",
"voice": "af_heart",
"h": "dddaf1e89d5d"
},
"c-s3-l7": {
"url": "audio/c-s3-l7.m4a",
"voice": "af_heart",
"h": "f2f22c17ad80"
},
"c-s3-l9": {
"url": "audio/c-s3-l9.m4a",
"voice": "af_heart",
"h": "003c8b50dca1"
},
"c-sc4-intro": {
"url": "audio/c-sc4-intro.m4a",
"voice": "af_heart",
"h": "babc5c732847"
},
"c-s4-l1": {
"url": "audio/c-s4-l1.m4a",
"voice": "af_heart",
"h": "26b09e0d0f65"
},
"c-s4-l2": {
"url": "audio/c-s4-l2.m4a",
"voice": "af_heart",
"h": "61cf217b195b"
},
"c-s4-l3": {
"url": "audio/c-s4-l3.m4a",
"voice": "af_heart",
"h": "33e308da88fa"
},
"c-s4-l4": {
"url": "audio/c-s4-l4.m4a",
"voice": "af_heart",
"h": "28a3588c5f59"
},
"c-s4-l5": {
"url": "audio/c-s4-l5.m4a",
"voice": "af_heart",
"h": "30afd32803e8"
},
"c-s4-l7": {
"url": "audio/c-s4-l7.m4a",
"voice": "af_heart",
"h": "c69a702bed62"
},
"c-sc5-intro": {
"url": "audio/c-sc5-intro.m4a",
"voice": "af_heart",
"h": "2322057d6eed"
},
"c-s5-l0": {
"url": "audio/c-s5-l0.m4a",
"voice": "af_heart",
"h": "3c26562f07f6"
},
"c-s5-l2": {
"url": "audio/c-s5-l2.m4a",
"voice": "af_heart",
"h": "69a9ff3f4a59"
},
"c-s5-l4": {
"url": "audio/c-s5-l4.m4a",
"voice": "af_heart",
"h": "e51df5dea89a"
},
"c-s5-l6": {
"url": "audio/c-s5-l6.m4a",
"voice": "af_heart",
"h": "ff1c3cb59176"
},
"c-s5-l8": {
"url": "audio/c-s5-l8.m4a",
"voice": "af_heart",
"h": "a28ecc780153"
},
"c-s5-l10": {
"url": "audio/c-s5-l10.m4a",
"voice": "af_heart",
"h": "365d2e799c7f"
},
"c-sc6-intro": {
"url": "audio/c-sc6-intro.m4a",
"voice": "af_heart",
"h": "0b167d7c51fd"
},
"c-s6-l1": {
"url": "audio/c-s6-l1.m4a",
"voice": "af_heart",
"h": "bb71b2727d03"
},
"c-s6-l3": {
"url": "audio/c-s6-l3.m4a",
"voice": "af_heart",
"h": "941ae33f8b85"
},
"c-s6-l5": {
"url": "audio/c-s6-l5.m4a",
"voice": "af_heart",
"h": "984ea6a9b98e"
},
"c-s6-l7": {
"url": "audio/c-s6-l7.m4a",
"voice": "af_heart",
"h": "f6af19fea31b"
},
"c-s6-l9": {
"url": "audio/c-s6-l9.m4a",
"voice": "af_heart",
"h": "7380ff4e877b"
},
"c-sc7-intro": {
"url": "audio/c-sc7-intro.m4a",
"voice": "af_heart",
"h": "31245fd322c6"
},
"c-s7-l2": {
"url": "audio/c-s7-l2.m4a",
"voice": "af_heart",
"h": "787f201b44be"
},
"c-s7-l3": {
"url": "audio/c-s7-l3.m4a",
"voice": "af_heart",
"h": "52e3162f7a00"
},
"c-s7-l4": {
"url": "audio/c-s7-l4.m4a",
"voice": "af_heart",
"h": "f8bd40590ede"
},
"c-s7-l6": {
"url": "audio/c-s7-l6.m4a",
"voice": "af_heart",
"h": "8bc31bd3c8f6"
},
"c-s7-l8": {
"url": "audio/c-s7-l8.m4a",
"voice": "af_heart",
"h": "24e75de7c3c1"
},
"c-sc8-intro": {
"url": "audio/c-sc8-intro.m4a",
"voice": "af_heart",
"h": "e0230b296bed"
},
"c-s8-l1": {
"url": "audio/c-s8-l1.m4a",
"voice": "af_heart",
"h": "22f5f3ac2268"
},
"c-s8-l3": {
"url": "audio/c-s8-l3.m4a",
"voice": "af_heart",
"h": "4b8c365d0c53"
},
"c-s8-l5": {
"url": "audio/c-s8-l5.m4a",
"voice": "af_heart",
"h": "44f0a35cf0eb"
},
"c-s8-l7": {
"url": "audio/c-s8-l7.m4a",
"voice": "af_heart",
"h": "2a00d994ba2f"
},
"c-s8-l9": {
"url": "audio/c-s8-l9.m4a",
"voice": "af_heart",
"h": "d2551c26ec61"
},
"c-s8-l12": {
"url": "audio/c-s8-l12.m4a",
"voice": "af_heart",
"h": "f9796075c97b"
},
"c-sc9-intro": {
"url": "audio/c-sc9-intro.m4a",
"voice": "af_heart",
"h": "fb01f8ee3849"
},
"c-s9-l1": {
"url": "audio/c-s9-l1.m4a",
"voice": "af_heart",
"h": "dab8b67343d9"
},
"c-s9-l2": {
"url": "audio/c-s9-l2.m4a",
"voice": "af_heart",
"h": "24d9b06681d5"
},
"c-s9-l4": {
"url": "audio/c-s9-l4.m4a",
"voice": "af_heart",
"h": "35eb284e1166"
},
"c-s9-l6": {
"url": "audio/c-s9-l6.m4a",
"voice": "af_heart",
"h": "0be3268aff03"
},
"c-s9-l8": {
"url": "audio/c-s9-l8.m4a",
"voice": "af_heart",
"h": "7a56bb4b8a50"
},
"c-s9-l10": {
"url": "audio/c-s9-l10.m4a",
"voice": "af_heart",
"h": "963d8e6e190d"
},
"c-s9-l12": {
"url": "audio/c-s9-l12.m4a",
"voice": "af_heart",
"h": "903f21e21728"
},
"c-sc10-intro": {
"url": "audio/c-sc10-intro.m4a",
"voice": "af_heart",
"h": "c87bbf76b921"
},
"c-s10-l1": {
"url": "audio/c-s10-l1.m4a",
"voice": "af_heart",
"h": "6182fe713ed7"
},
"c-s10-l3": {
"url": "audio/c-s10-l3.m4a",
"voice": "af_heart",
"h": "4432ef593afc"
},
"c-s10-l5": {
"url": "audio/c-s10-l5.m4a",
"voice": "af_heart",
"h": "1c1a10158c88"
},
"c-s10-l7": {
"url": "audio/c-s10-l7.m4a",
"voice": "af_heart",
"h": "0e9e76ea0fb1"
},
"c-s10-l9": {
"url": "audio/c-s10-l9.m4a",
"voice": "af_heart",
"h": "da3319d7e4ce"
},
"c-s10-l11": {
"url": "audio/c-s10-l11.m4a",
"voice": "af_heart",
"h": "b7270c51c55d"
},
"c-sc11-intro": {
"url": "audio/c-sc11-intro.m4a",
"voice": "af_heart",
"h": "38193ded1471"
},
"c-s11-l0": {
"url": "audio/c-s11-l0.m4a",
"voice": "af_heart",
"h": "0d4c863475d3"
},
"c-s11-l3": {
"url": "audio/c-s11-l3.m4a",
"voice": "af_heart",
"h": "ceb36f8e510b"
},
"c-s11-l5": {
"url": "audio/c-s11-l5.m4a",
"voice": "af_heart",
"h": "b4d94f3f431e"
},
"c-s11-l6": {
"url": "audio/c-s11-l6.m4a",
"voice": "af_heart",
"h": "598f887abaf8"
},
"c-s11-l8": {
"url": "audio/c-s11-l8.m4a",
"voice": "af_heart",
"h": "63f2d5952415"
},
"c-sc12-intro": {
"url": "audio/c-sc12-intro.m4a",
"voice": "af_heart",
"h": "1c8a0ffa0dbf"
},
"c-s12-l1": {
"url": "audio/c-s12-l1.m4a",
"voice": "af_heart",
"h": "8048134234d1"
},
"c-s12-l2": {
"url": "audio/c-s12-l2.m4a",
"voice": "af_heart",
"h": "da75ac0a072a"
},
"c-s12-l4": {
"url": "audio/c-s12-l4.m4a",
"voice": "af_heart",
"h": "de34d7d0b0db"
},
"c-s12-l6": {
"url": "audio/c-s12-l6.m4a",
"voice": "af_heart",
"h": "0183cc0a3ace"
},
"c-s12-l8": {
"url": "audio/c-s12-l8.m4a",
"voice": "af_heart",
"h": "31cc7d7b70f3"
},
"c-sc13-intro": {
"url": "audio/c-sc13-intro.m4a",
"voice": "af_heart",
"h": "94facda14b34"
},
"c-s13-l0": {
"url": "audio/c-s13-l0.m4a",
"voice": "af_heart",
"h": "60b0a35d8cfd"
},
"c-s13-l2": {
"url": "audio/c-s13-l2.m4a",
"voice": "af_heart",
"h": "114f4163062d"
},
"c-s13-l3": {
"url": "audio/c-s13-l3.m4a",
"voice": "af_heart",
"h": "4b602bc7b7b8"
},
"c-s13-l5": {
"url": "audio/c-s13-l5.m4a",
"voice": "af_heart",
"h": "c716be2ec83b"
},
"c-s13-l7": {
"url": "audio/c-s13-l7.m4a",
"voice": "af_heart",
"h": "eb9fb7986294"
},
"c-s13-l9": {
"url": "audio/c-s13-l9.m4a",
"voice": "af_heart",
"h": "1992880cc7e0"
},
"c-sc14-intro": {
"url": "audio/c-sc14-intro.m4a",
"voice": "af_heart",
"h": "1169814b1218"
},
"c-s14-l0": {
"url": "audio/c-s14-l0.m4a",
"voice": "af_heart",
"h": "3e79a48b7ac8"
},
"c-s14-l1": {
"url": "audio/c-s14-l1.m4a",
"voice": "af_heart",
"h": "f43a951f1559"
},
"c-s14-l3": {
"url": "audio/c-s14-l3.m4a",
"voice": "af_heart",
"h": "88b5f09997f9"
},
"c-s14-l5": {
"url": "audio/c-s14-l5.m4a",
"voice": "af_heart",
"h": "ccf321a01eea"
},
"c-s14-l6": {
"url": "audio/c-s14-l6.m4a",
"voice": "af_heart",
"h": "3b2adc44d789"
},
"c-s14-l8": {
"url": "audio/c-s14-l8.m4a",
"voice": "af_heart",
"h": "94f482b8c430"
},
"c-sc15-intro": {
"url": "audio/c-sc15-intro.m4a",
"voice": "af_heart",
"h": "2d1cfa121c7b"
},
"c-s15-l2": {
"url": "audio/c-s15-l2.m4a",
"voice": "af_heart",
"h": "c3784e7ab9e1"
},
"c-s15-l3": {
"url": "audio/c-s15-l3.m4a",
"voice": "af_heart",
"h": "da659b6ec54b"
},
"c-s15-l6": {
"url": "audio/c-s15-l6.m4a",
"voice": "af_heart",
"h": "4bf980e2f7e5"
},
"c-s15-l8": {
"url": "audio/c-s15-l8.m4a",
"voice": "af_heart",
"h": "afb8b3344dfa"
},
"c-s15-l10": {
"url": "audio/c-s15-l10.m4a",
"voice": "af_heart",
"h": "148ae9d0eba5"
},
"c-sc16-intro": {
"url": "audio/c-sc16-intro.m4a",
"voice": "af_heart",
"h": "20bf166cb135"
},
"c-s16-l1": {
"url": "audio/c-s16-l1.m4a",
"voice": "af_heart",
"h": "62522b35fcb5"
},
"c-s16-l3": {
"url": "audio/c-s16-l3.m4a",
"voice": "af_heart",
"h": "98f8d50f5264"
},
"c-s16-l5": {
"url": "audio/c-s16-l5.m4a",
"voice": "af_heart",
"h": "08e014caeff9"
},
"c-s16-l7": {
"url": "audio/c-s16-l7.m4a",
"voice": "af_heart",
"h": "b05602cf7cfb"
},
"c-sc17-intro": {
"url": "audio/c-sc17-intro.m4a",
"voice": "af_heart",
"h": "17d9744c9317"
},
"c-s17-l1": {
"url": "audio/c-s17-l1.m4a",
"voice": "af_heart",
"h": "7205d4b3a7ca"
},
"c-s17-l3": {
"url": "audio/c-s17-l3.m4a",
"voice": "af_heart",
"h": "a89594d4e0ed"
},
"c-s17-l5": {
"url": "audio/c-s17-l5.m4a",
"voice": "af_heart",
"h": "75d75712283f"
},
"c-s17-l7": {
"url": "audio/c-s17-l7.m4a",
"voice": "af_heart",
"h": "cd70914672b8"
},
"c-sc18-intro": {
"url": "audio/c-sc18-intro.m4a",
"voice": "af_heart",
"h": "0936835f08ae"
},
"c-s18-l2": {
"url": "audio/c-s18-l2.m4a",
"voice": "af_heart",
"h": "e34adf2de671"
},
"c-s18-l3": {
"url": "audio/c-s18-l3.m4a",
"voice": "af_heart",
"h": "1d2f79600a59"
},
"c-s18-l5": {
"url": "audio/c-s18-l5.m4a",
"voice": "af_heart",
"h": "554e404dcc2e"
},
"c-s18-l7": {
"url": "audio/c-s18-l7.m4a",
"voice": "af_heart",
"h": "f592cff2b7f6"
},
"c-sc19-intro": {
"url": "audio/c-sc19-intro.m4a",
"voice": "af_heart",
"h": "0ad258e40ecc"
},
"c-s19-l0": {
"url": "audio/c-s19-l0.m4a",
"voice": "af_heart",
"h": "c608ca4cd0e4"
},
"c-s19-l1": {
"url": "audio/c-s19-l1.m4a",
"voice": "af_heart",
"h": "a1e3565828c4"
},
"c-s19-l3": {
"url": "audio/c-s19-l3.m4a",
"voice": "af_heart",
"h": "df3d93358552"
},
"c-s19-l5": {
"url": "audio/c-s19-l5.m4a",
"voice": "af_heart",
"h": "dca0626f0b00"
},
"c-s19-l7": {
"url": "audio/c-s19-l7.m4a",
"voice": "af_heart",
"h": "c47fbf10c4b6"
},
"c-s19-l9": {
"url": "audio/c-s19-l9.m4a",
"voice": "af_heart",
"h": "b262d409f5c3"
},
"c-sc20-intro": {
"url": "audio/c-sc20-intro.m4a",
"voice": "af_heart",
"h": "95e455ed79a9"
},
"c-s20-l0": {
"url": "audio/c-s20-l0.m4a",
"voice": "af_heart",
"h": "1459f135f724"
},
"c-s20-l2": {
"url": "audio/c-s20-l2.m4a",
"voice": "af_heart",
"h": "c02729f91ddc"
},
"c-s20-l6": {
"url": "audio/c-s20-l6.m4a",
"voice": "af_heart",
"h": "65229655a931"
},
"c-s20-l8": {
"url": "audio/c-s20-l8.m4a",
"voice": "af_heart",
"h": "afe2577711c4"
},
"c-sc21-intro": {
"url": "audio/c-sc21-intro.m4a",
"voice": "af_heart",
"h": "1f8abdc743cf"
},
"c-s21-l0": {
"url": "audio/c-s21-l0.m4a",
"voice": "af_heart",
"h": "433e724b4116"
},
"c-s21-l2": {
"url": "audio/c-s21-l2.m4a",
"voice": "af_heart",
"h": "cbd5356056ca"
},
"c-s21-l4": {
"url": "audio/c-s21-l4.m4a",
"voice": "af_heart",
"h": "63f46de6892c"
},
"c-s21-l6": {
"url": "audio/c-s21-l6.m4a",
"voice": "af_heart",
"h": "e3ce1472438c"
},
"c-sc22-intro": {
"url": "audio/c-sc22-intro.m4a",
"voice": "af_heart",
"h": "ecf6dcb28553"
},
"c-s22-l0": {
"url": "audio/c-s22-l0.m4a",
"voice": "af_heart",
"h": "12bdedd9700b"
},
"c-s22-l2": {
"url": "audio/c-s22-l2.m4a",
"voice": "af_heart",
"h": "df4a07b28b9c"
},
"c-s22-l5": {
"url": "audio/c-s22-l5.m4a",
"voice": "af_heart",
"h": "c0f102d9461d"
},
"c-s22-l7": {
"url": "audio/c-s22-l7.m4a",
"voice": "af_heart",
"h": "27edb63d60ff"
},
"c-sc23-intro": {
"url": "audio/c-sc23-intro.m4a",
"voice": "af_heart",
"h": "21fae4a7db3a"
},
"c-s23-l0": {
"url": "audio/c-s23-l0.m4a",
"voice": "af_heart",
"h": "e338dc783d4d"
},
"c-s23-l2": {
"url": "audio/c-s23-l2.m4a",
"voice": "af_heart",
"h": "da93abdc72ff"
},
"c-s23-l3": {
"url": "audio/c-s23-l3.m4a",
"voice": "af_heart",
"h": "8d9092299387"
},
"c-s23-l4": {
"url": "audio/c-s23-l4.m4a",
"voice": "af_heart",
"h": "3d83801a5f6c"
},
"c-s23-l6": {
"url": "audio/c-s23-l6.m4a",
"voice": "af_heart",
"h": "b52147e37f06"
},
"c-sc24-intro": {
"url": "audio/c-sc24-intro.m4a",
"voice": "af_heart",
"h": "24204b999676"
},
"c-s24-l1": {
"url": "audio/c-s24-l1.m4a",
"voice": "af_heart",
"h": "e9d497416119"
},
"c-s24-l2": {
"url": "audio/c-s24-l2.m4a",
"voice": "af_heart",
"h": "58dfe754feab"
},
"c-s24-l4": {
"url": "audio/c-s24-l4.m4a",
"voice": "af_heart",
"h": "d8ea269a01ec"
},
"c-s24-l5": {
"url": "audio/c-s24-l5.m4a",
"voice": "af_heart",
"h": "33dd211d80b7"
},
"c-sc25-intro": {
"url": "audio/c-sc25-intro.m4a",
"voice": "af_heart",
"h": "2c4a1d0ed213"
},
"c-s25-l1": {
"url": "audio/c-s25-l1.m4a",
"voice": "af_heart",
"h": "8b9ff9a54836"
},
"c-s25-l3": {
"url": "audio/c-s25-l3.m4a",
"voice": "af_heart",
"h": "903385249ceb"
},
"c-s25-l5": {
"url": "audio/c-s25-l5.m4a",
"voice": "af_heart",
"h": "65ef6e2f5337"
},
"c-lesson0-intro": {
"url": "audio/c-lesson0-intro.m4a",
"voice": "af_heart",
"h": "13d905dcac8d"
},
"c-lesson0-drill": {
"url": "audio/c-lesson0-drill.m4a",
"voice": "af_heart",
"h": "1d0dc981565d"
},
"c-lesson0-rule": {
"url": "audio/c-lesson0-rule.m4a",
"voice": "af_heart",
"h": "1fd28e858beb"
},
"c-lesson0-p0-note": {
"url": "audio/c-lesson0-p0-note.m4a",
"voice": "af_heart",
"h": "af00738f7748"
},
"c-lesson0-p1-note": {
"url": "audio/c-lesson0-p1-note.m4a",
"voice": "af_heart",
"h": "ac4c5286d8dd"
},
"c-lesson1-intro": {
"url": "audio/c-lesson1-intro.m4a",
"voice": "af_heart",
"h": "0edf29a5ae06"
},
"c-lesson1-drill": {
"url": "audio/c-lesson1-drill.m4a",
"voice": "af_heart",
"h": "b91450c4bedc"
},
"c-lesson1-rule": {
"url": "audio/c-lesson1-rule.m4a",
"voice": "af_heart",
"h": "ad00eaa33fee"
},
"c-lesson1-p0-note": {
"url": "audio/c-lesson1-p0-note.m4a",
"voice": "af_heart",
"h": "d15248c4b96c"
},
"c-lesson1-p1-note": {
"url": "audio/c-lesson1-p1-note.m4a",
"voice": "af_heart",
"h": "261ab03d1b38"
},
"c-lesson2-intro": {
"url": "audio/c-lesson2-intro.m4a",
"voice": "af_heart",
"h": "2274bceb0cf7"
},
"c-lesson2-drill": {
"url": "audio/c-lesson2-drill.m4a",
"voice": "af_heart",
"h": "a39bf8b01b41"
},
"c-lesson2-rule": {
"url": "audio/c-lesson2-rule.m4a",
"voice": "af_heart",
"h": "8cf35b0a7c00"
},
"c-lesson2-p0-note": {
"url": "audio/c-lesson2-p0-note.m4a",
"voice": "af_heart",
"h": "4607feba5ed5"
},
"c-lesson2-p1-note": {
"url": "audio/c-lesson2-p1-note.m4a",
"voice": "af_heart",
"h": "660851e222fd"
},
"c-lesson3-intro": {
"url": "audio/c-lesson3-intro.m4a",
"voice": "af_heart",
"h": "21f52579c86d"
},
"c-lesson3-drill": {
"url": "audio/c-lesson3-drill.m4a",
"voice": "af_heart",
"h": "0b8bbeee7204"
},
"c-lesson3-rule": {
"url": "audio/c-lesson3-rule.m4a",
"voice": "af_heart",
"h": "959f1fc5a20f"
},
"c-lesson3-p0-note": {
"url": "audio/c-lesson3-p0-note.m4a",
"voice": "af_heart",
"h": "fe638ef06009"
},
"c-lesson3-p1-note": {
"url": "audio/c-lesson3-p1-note.m4a",
"voice": "af_heart",
"h": "215bd3cefa62"
},
"c-lesson3-p2-note": {
"url": "audio/c-lesson3-p2-note.m4a",
"voice": "af_heart",
"h": "40633a8643ad"
},
"c-lesson4-intro": {
"url": "audio/c-lesson4-intro.m4a",
"voice": "af_heart",
"h": "e9f9ac3f7701"
},
"c-lesson4-drill": {
"url": "audio/c-lesson4-drill.m4a",
"voice": "af_heart",
"h": "fa91178de911"
},
"c-lesson4-rule": {
"url": "audio/c-lesson4-rule.m4a",
"voice": "af_heart",
"h": "58f8af0057be"
},
"c-lesson4-p0-note": {
"url": "audio/c-lesson4-p0-note.m4a",
"voice": "af_heart",
"h": "d0c46d64eb51"
},
"c-lesson4-p1-note": {
"url": "audio/c-lesson4-p1-note.m4a",
"voice": "af_heart",
"h": "f6e61389f896"
},
"c-lesson5-intro": {
"url": "audio/c-lesson5-intro.m4a",
"voice": "af_heart",
"h": "f49cd45539ee"
},
"c-lesson5-drill": {
"url": "audio/c-lesson5-drill.m4a",
"voice": "af_heart",
"h": "bc2c82f6fb26"
},
"c-lesson5-rule": {
"url": "audio/c-lesson5-rule.m4a",
"voice": "af_heart",
"h": "bec160dffa24"
},
"c-lesson5-p0-note": {
"url": "audio/c-lesson5-p0-note.m4a",
"voice": "af_heart",
"h": "dadb1c3777f7"
},
"c-lesson5-p1-note": {
"url": "audio/c-lesson5-p1-note.m4a",
"voice": "af_heart",
"h": "b482da8bc667"
},
"c-lesson5-p2-note": {
"url": "audio/c-lesson5-p2-note.m4a",
"voice": "af_heart",
"h": "37c6a4abb439"
},
"c-lesson6-intro": {
"url": "audio/c-lesson6-intro.m4a",
"voice": "af_heart",
"h": "7a2d24317aa4"
},
"c-lesson6-drill": {
"url": "audio/c-lesson6-drill.m4a",
"voice": "af_heart",
"h": "c3d94e5b899c"
},
"c-lesson6-rule": {
"url": "audio/c-lesson6-rule.m4a",
"voice": "af_heart",
"h": "74c777681676"
},
"c-lesson6-p0-note": {
"url": "audio/c-lesson6-p0-note.m4a",
"voice": "af_heart",
"h": "a60cf8091011"
},
"c-lesson6-p1-note": {
"url": "audio/c-lesson6-p1-note.m4a",
"voice": "af_heart",
"h": "88c287b7e753"
},
"c-lesson6-p2-note": {
"url": "audio/c-lesson6-p2-note.m4a",
"voice": "af_heart",
"h": "410ef00eda9e"
},
"c-lesson7-intro": {
"url": "audio/c-lesson7-intro.m4a",
"voice": "af_heart",
"h": "431b6685a800"
},
"c-lesson7-drill": {
"url": "audio/c-lesson7-drill.m4a",
"voice": "af_heart",
"h": "90d6c059fc4b"
},
"c-lesson7-rule": {
"url": "audio/c-lesson7-rule.m4a",
"voice": "af_heart",
"h": "c206c1262c23"
},
"c-lesson7-p0-note": {
"url": "audio/c-lesson7-p0-note.m4a",
"voice": "af_heart",
"h": "b75fae0b0a96"
},
"c-lesson7-p1-note": {
"url": "audio/c-lesson7-p1-note.m4a",
"voice": "af_heart",
"h": "2c522306dd0f"
},
"c-lesson8-intro": {
"url": "audio/c-lesson8-intro.m4a",
"voice": "af_heart",
"h": "06784e939edb"
},
"c-lesson8-drill": {
"url": "audio/c-lesson8-drill.m4a",
"voice": "af_heart",
"h": "7ed458026501"
},
"c-lesson8-rule": {
"url": "audio/c-lesson8-rule.m4a",
"voice": "af_heart",
"h": "281f63d05d11"
},
"c-lesson8-p0-note": {
"url": "audio/c-lesson8-p0-note.m4a",
"voice": "af_heart",
"h": "edf2bfb1d75d"
},
"c-lesson8-p1-note": {
"url": "audio/c-lesson8-p1-note.m4a",
"voice": "af_heart",
"h": "d560be640089"
},
"c-lesson9-intro": {
"url": "audio/c-lesson9-intro.m4a",
"voice": "af_heart",
"h": "4568c62eba07"
},
"c-lesson9-drill": {
"url": "audio/c-lesson9-drill.m4a",
"voice": "af_heart",
"h": "c1beaff26d39"
},
"c-lesson9-rule": {
"url": "audio/c-lesson9-rule.m4a",
"voice": "af_heart",
"h": "08e95130e4fc"
},
"c-lesson9-p0-note": {
"url": "audio/c-lesson9-p0-note.m4a",
"voice": "af_heart",
"h": "f30e1116a0a5"
},
"c-lesson9-p1-note": {
"url": "audio/c-lesson9-p1-note.m4a",
"voice": "af_heart",
"h": "0f1b07d5f5ef"
},
"c-lesson10-intro": {
"url": "audio/c-lesson10-intro.m4a",
"voice": "af_heart",
"h": "369b5831865f"
},
"c-lesson10-drill": {
"url": "audio/c-lesson10-drill.m4a",
"voice": "af_heart",
"h": "39a11ddf27a4"
},
"c-lesson10-rule": {
"url": "audio/c-lesson10-rule.m4a",
"voice": "af_heart",
"h": "84c65d97fd48"
},
"c-lesson10-p0-note": {
"url": "audio/c-lesson10-p0-note.m4a",
"voice": "af_heart",
"h": "09072fa866e0"
},
"c-lesson10-p1-note": {
"url": "audio/c-lesson10-p1-note.m4a",
"voice": "af_heart",
"h": "829faa16f3be"
},
"c-lesson11-intro": {
"url": "audio/c-lesson11-intro.m4a",
"voice": "af_heart",
"h": "ae2f964e8195"
},
"c-lesson11-drill": {
"url": "audio/c-lesson11-drill.m4a",
"voice": "af_heart",
"h": "59b2f6f01fd8"
},
"c-lesson11-rule": {
"url": "audio/c-lesson11-rule.m4a",
"voice": "af_heart",
"h": "de0e40fba312"
},
"c-lesson11-p0-note": {
"url": "audio/c-lesson11-p0-note.m4a",
"voice": "af_heart",
"h": "b5425732b2ef"
},
"c-lesson11-p1-note": {
"url": "audio/c-lesson11-p1-note.m4a",
"voice": "af_heart",
"h": "6b09241d03d4"
},
"c-lesson12-intro": {
"url": "audio/c-lesson12-intro.m4a",
"voice": "af_heart",
"h": "d8d8b6afa128"
},
"c-lesson12-drill": {
"url": "audio/c-lesson12-drill.m4a",
"voice": "af_heart",
"h": "13bddc7c90dc"
},
"c-lesson12-rule": {
"url": "audio/c-lesson12-rule.m4a",
"voice": "af_heart",
"h": "714298ce61fa"
},
"c-lesson12-p0-note": {
"url": "audio/c-lesson12-p0-note.m4a",
"voice": "af_heart",
"h": "b569d70902b9"
},
"c-lesson12-p1-note": {
"url": "audio/c-lesson12-p1-note.m4a",
"voice": "af_heart",
"h": "7571c5b99acd"
},
"c-lesson13-intro": {
"url": "audio/c-lesson13-intro.m4a",
"voice": "af_heart",
"h": "823b4a667aa4"
},
"c-lesson13-drill": {
"url": "audio/c-lesson13-drill.m4a",
"voice": "af_heart",
"h": "332ebff8ad30"
},
"c-lesson13-rule": {
"url": "audio/c-lesson13-rule.m4a",
"voice": "af_heart",
"h": "22b661361a7f"
},
"c-lesson13-p0-note": {
"url": "audio/c-lesson13-p0-note.m4a",
"voice": "af_heart",
"h": "df3d93358552"
},
"c-lesson13-p1-note": {
"url": "audio/c-lesson13-p1-note.m4a",
"voice": "af_heart",
"h": "d52ade12772b"
},
"c-lesson14-intro": {
"url": "audio/c-lesson14-intro.m4a",
"voice": "af_heart",
"h": "03ac628aa807"
},
"c-lesson14-drill": {
"url": "audio/c-lesson14-drill.m4a",
"voice": "af_heart",
"h": "43e635e283aa"
},
"c-lesson14-rule": {
"url": "audio/c-lesson14-rule.m4a",
"voice": "af_heart",
"h": "e467b67677fc"
},
"c-lesson14-p0-note": {
"url": "audio/c-lesson14-p0-note.m4a",
"voice": "af_heart",
"h": "a2e73d127485"
},
"c-lesson14-p1-note": {
"url": "audio/c-lesson14-p1-note.m4a",
"voice": "af_heart",
"h": "f8af1283f190"
},
"c-lesson14-p2-note": {
"url": "audio/c-lesson14-p2-note.m4a",
"voice": "af_heart",
"h": "ee36db431197"
},
"c-lesson15-intro": {
"url": "audio/c-lesson15-intro.m4a",
"voice": "af_heart",
"h": "069655f56d4b"
},
"c-lesson15-drill": {
"url": "audio/c-lesson15-drill.m4a",
"voice": "af_heart",
"h": "d22b7014a43e"
},
"c-lesson15-rule": {
"url": "audio/c-lesson15-rule.m4a",
"voice": "af_heart",
"h": "a15d837e2178"
},
"c-lesson15-p0-note": {
"url": "audio/c-lesson15-p0-note.m4a",
"voice": "af_heart",
"h": "6a020246658a"
},
"c-lesson15-p1-note": {
"url": "audio/c-lesson15-p1-note.m4a",
"voice": "af_heart",
"h": "d74caeddd5a0"
},
"c-lesson15-p2-note": {
"url": "audio/c-lesson15-p2-note.m4a",
"voice": "af_heart",
"h": "2bcd0be9bc50"
},
"c-lesson16-intro": {
"url": "audio/c-lesson16-intro.m4a",
"voice": "af_heart",
"h": "a7dc5baeb7c6"
},
"c-lesson16-drill": {
"url": "audio/c-lesson16-drill.m4a",
"voice": "af_heart",
"h": "3fd7ae1c40b3"
},
"c-lesson16-rule": {
"url": "audio/c-lesson16-rule.m4a",
"voice": "af_heart",
"h": "1347f383a0a0"
},
"c-lesson16-p0-note": {
"url": "audio/c-lesson16-p0-note.m4a",
"voice": "af_heart",
"h": "ad0fa71e9c19"
},
"c-lesson16-p1-note": {
"url": "audio/c-lesson16-p1-note.m4a",
"voice": "af_heart",
"h": "3129ed31522b"
},
"c-lesson17-intro": {
"url": "audio/c-lesson17-intro.m4a",
"voice": "af_heart",
"h": "b1b1bbe6889d"
},
"c-lesson17-drill": {
"url": "audio/c-lesson17-drill.m4a",
"voice": "af_heart",
"h": "452199886609"
},
"c-lesson17-rule": {
"url": "audio/c-lesson17-rule.m4a",
"voice": "af_heart",
"h": "f66475b1a45a"
},
"c-lesson17-p0-note": {
"url": "audio/c-lesson17-p0-note.m4a",
"voice": "af_heart",
"h": "89be7846a6d5"
},
"c-lesson17-p1-note": {
"url": "audio/c-lesson17-p1-note.m4a",
"voice": "af_heart",
"h": "48a97243fe78"
},
"c-lesson18-intro": {
"url": "audio/c-lesson18-intro.m4a",
"voice": "af_heart",
"h": "c0d07a51c5ec"
},
"c-lesson18-drill": {
"url": "audio/c-lesson18-drill.m4a",
"voice": "af_heart",
"h": "14ecea02558c"
},
"c-lesson18-rule": {
"url": "audio/c-lesson18-rule.m4a",
"voice": "af_heart",
"h": "56ea4c323ee0"
},
"c-lesson18-p0-note": {
"url": "audio/c-lesson18-p0-note.m4a",
"voice": "af_heart",
"h": "8a5e11d5d6e7"
},
"c-lesson18-p1-note": {
"url": "audio/c-lesson18-p1-note.m4a",
"voice": "af_heart",
"h": "20f2d551696c"
},
"c-lesson19-intro": {
"url": "audio/c-lesson19-intro.m4a",
"voice": "af_heart",
"h": "92991a7c32b1"
},
"c-lesson19-drill": {
"url": "audio/c-lesson19-drill.m4a",
"voice": "af_heart",
"h": "c7a4beb22a7e"
},
"c-lesson19-rule": {
"url": "audio/c-lesson19-rule.m4a",
"voice": "af_heart",
"h": "1fb67d90304f"
},
"c-lesson19-p0-note": {
"url": "audio/c-lesson19-p0-note.m4a",
"voice": "af_heart",
"h": "27edb63d60ff"
},
"c-lesson19-p1-note": {
"url": "audio/c-lesson19-p1-note.m4a",
"voice": "af_heart",
"h": "002e7f20e57b"
},
"c-lesson20-intro": {
"url": "audio/c-lesson20-intro.m4a",
"voice": "af_heart",
"h": "add659ab2135"
},
"c-lesson20-drill": {
"url": "audio/c-lesson20-drill.m4a",
"voice": "af_heart",
"h": "c149f8efb7ce"
},
"c-lesson20-rule": {
"url": "audio/c-lesson20-rule.m4a",
"voice": "af_heart",
"h": "10782964c257"
},
"c-lesson20-p0-note": {
"url": "audio/c-lesson20-p0-note.m4a",
"voice": "af_heart",
"h": "58189ea5da23"
},
"c-lesson20-p1-note": {
"url": "audio/c-lesson20-p1-note.m4a",
"voice": "af_heart",
"h": "d06d62451455"
},
"c-lesson21-intro": {
"url": "audio/c-lesson21-intro.m4a",
"voice": "af_heart",
"h": "1fd39b6c99a2"
},
"c-lesson21-drill": {
"url": "audio/c-lesson21-drill.m4a",
"voice": "af_heart",
"h": "fff8e0b40aef"
},
"c-lesson21-rule": {
"url": "audio/c-lesson21-rule.m4a",
"voice": "af_heart",
"h": "0a41d0c210cc"
},
"c-lesson21-p0-note": {
"url": "audio/c-lesson21-p0-note.m4a",
"voice": "af_heart",
"h": "cd619ecd78c7"
},
"c-lesson21-p1-note": {
"url": "audio/c-lesson21-p1-note.m4a",
"voice": "af_heart",
"h": "264ee82ebce3"
},
"c-lesson22-intro": {
"url": "audio/c-lesson22-intro.m4a",
"voice": "af_heart",
"h": "51ecfbb77a03"
},
"c-lesson22-drill": {
"url": "audio/c-lesson22-drill.m4a",
"voice": "af_heart",
"h": "3d5086eafd3d"
},
"c-lesson22-rule": {
"url": "audio/c-lesson22-rule.m4a",
"voice": "af_heart",
"h": "accf2c9eb15f"
},
"c-lesson22-p0-note": {
"url": "audio/c-lesson22-p0-note.m4a",
"voice": "af_heart",
"h": "498c62d8f3b4"
},
"c-lesson22-p1-note": {
"url": "audio/c-lesson22-p1-note.m4a",
"voice": "af_heart",
"h": "2196eb76a70c"
},
"c-lesson0-q0": {
"url": "audio/c-lesson0-q0.m4a",
"voice": "af_heart",
"h": "b501d212fdda"
},
"c-lesson0-q0-why": {
"url": "audio/c-lesson0-q0-why.m4a",
"voice": "af_heart",
"h": "4bb514ea3ba9"
},
"c-lesson1-q0": {
"url": "audio/c-lesson1-q0.m4a",
"voice": "af_heart",
"h": "82fdfaaae4e3"
},
"c-lesson1-q0-why": {
"url": "audio/c-lesson1-q0-why.m4a",
"voice": "af_heart",
"h": "96b52c60ef5f"
},
"c-lesson1-q1": {
"url": "audio/c-lesson1-q1.m4a",
"voice": "af_heart",
"h": "a49fb50f9f13"
},
"c-lesson1-q1-why": {
"url": "audio/c-lesson1-q1-why.m4a",
"voice": "af_heart",
"h": "633f9e41fe0c"
},
"c-lesson2-q0": {
"url": "audio/c-lesson2-q0.m4a",
"voice": "af_heart",
"h": "69550340b73c"
},
"c-lesson2-q0-why": {
"url": "audio/c-lesson2-q0-why.m4a",
"voice": "af_heart",
"h": "52a356b13e4e"
},
"c-lesson2-q1": {
"url": "audio/c-lesson2-q1.m4a",
"voice": "af_heart",
"h": "bea0177b60aa"
},
"c-lesson2-q1-why": {
"url": "audio/c-lesson2-q1-why.m4a",
"voice": "af_heart",
"h": "814d97015c6b"
},
"c-lesson3-q0": {
"url": "audio/c-lesson3-q0.m4a",
"voice": "af_heart",
"h": "d4754d6f7e54"
},
"c-lesson3-q0-why": {
"url": "audio/c-lesson3-q0-why.m4a",
"voice": "af_heart",
"h": "07a5b45cf095"
},
"c-lesson3-q1": {
"url": "audio/c-lesson3-q1.m4a",
"voice": "af_heart",
"h": "8aa1ef719762"
},
"c-lesson3-q1-why": {
"url": "audio/c-lesson3-q1-why.m4a",
"voice": "af_heart",
"h": "dde0a9707c0c"
},
"c-lesson4-q0": {
"url": "audio/c-lesson4-q0.m4a",
"voice": "af_heart",
"h": "b19e38651cf7"
},
"c-lesson4-q0-why": {
"url": "audio/c-lesson4-q0-why.m4a",
"voice": "af_heart",
"h": "eab4079fa391"
},
"c-lesson5-q0": {
"url": "audio/c-lesson5-q0.m4a",
"voice": "af_heart",
"h": "a65ddf255f37"
},
"c-lesson5-q0-why": {
"url": "audio/c-lesson5-q0-why.m4a",
"voice": "af_heart",
"h": "3312c3fe895a"
},
"c-lesson6-q0": {
"url": "audio/c-lesson6-q0.m4a",
"voice": "af_heart",
"h": "d4754d6f7e54"
},
"c-lesson6-q0-why": {
"url": "audio/c-lesson6-q0-why.m4a",
"voice": "af_heart",
"h": "3f21d853cb97"
},
"c-lesson6-q1": {
"url": "audio/c-lesson6-q1.m4a",
"voice": "af_heart",
"h": "45d3b60aa67e"
},
"c-lesson6-q1-why": {
"url": "audio/c-lesson6-q1-why.m4a",
"voice": "af_heart",
"h": "9ea17c648c5f"
},
"c-lesson7-q0": {
"url": "audio/c-lesson7-q0.m4a",
"voice": "af_heart",
"h": "4528ec8ec3c1"
},
"c-lesson7-q0-why": {
"url": "audio/c-lesson7-q0-why.m4a",
"voice": "af_heart",
"h": "f3fd44dea52e"
},
"c-lesson8-q0": {
"url": "audio/c-lesson8-q0.m4a",
"voice": "af_heart",
"h": "fbbf63e4dca1"
},
"c-lesson8-q0-why": {
"url": "audio/c-lesson8-q0-why.m4a",
"voice": "af_heart",
"h": "b5b18494c6e5"
},
"c-lesson9-q0": {
"url": "audio/c-lesson9-q0.m4a",
"voice": "af_heart",
"h": "dcfff662bd6d"
},
"c-lesson9-q0-why": {
"url": "audio/c-lesson9-q0-why.m4a",
"voice": "af_heart",
"h": "6ef9be32c907"
},
"c-lesson9-q1": {
"url": "audio/c-lesson9-q1.m4a",
"voice": "af_heart",
"h": "578fdd5d2108"
},
"c-lesson9-q1-why": {
"url": "audio/c-lesson9-q1-why.m4a",
"voice": "af_heart",
"h": "d9bd099c9b57"
},
"c-lesson10-q0": {
"url": "audio/c-lesson10-q0.m4a",
"voice": "af_heart",
"h": "8536670445ec"
},
"c-lesson10-q0-why": {
"url": "audio/c-lesson10-q0-why.m4a",
"voice": "af_heart",
"h": "f1ebff153e67"
},
"c-lesson11-q0": {
"url": "audio/c-lesson11-q0.m4a",
"voice": "af_heart",
"h": "fdacb58f4b6a"
},
"c-lesson11-q0-why": {
"url": "audio/c-lesson11-q0-why.m4a",
"voice": "af_heart",
"h": "d454505c40eb"
},
"c-lesson12-q0": {
"url": "audio/c-lesson12-q0.m4a",
"voice": "af_heart",
"h": "0bb16310adcd"
},
"c-lesson12-q0-why": {
"url": "audio/c-lesson12-q0-why.m4a",
"voice": "af_heart",
"h": "7dc155b58073"
},
"c-lesson13-q0": {
"url": "audio/c-lesson13-q0.m4a",
"voice": "af_heart",
"h": "ec8f0085f906"
},
"c-lesson13-q0-why": {
"url": "audio/c-lesson13-q0-why.m4a",
"voice": "af_heart",
"h": "1b6e826dbf84"
},
"c-lesson13-q1": {
"url": "audio/c-lesson13-q1.m4a",
"voice": "af_heart",
"h": "33f3904506bd"
},
"c-lesson13-q1-why": {
"url": "audio/c-lesson13-q1-why.m4a",
"voice": "af_heart",
"h": "2f5fab5811ba"
},
"c-lesson14-q0": {
"url": "audio/c-lesson14-q0.m4a",
"voice": "af_heart",
"h": "4724b2d8803a"
},
"c-lesson14-q0-why": {
"url": "audio/c-lesson14-q0-why.m4a",
"voice": "af_heart",
"h": "43526f54263c"
},
"c-lesson14-q1": {
"url": "audio/c-lesson14-q1.m4a",
"voice": "af_heart",
"h": "5f107dd2c907"
},
"c-lesson14-q1-why": {
"url": "audio/c-lesson14-q1-why.m4a",
"voice": "af_heart",
"h": "23bba090b275"
},
"c-lesson15-q0": {
"url": "audio/c-lesson15-q0.m4a",
"voice": "af_heart",
"h": "363ee6a79af8"
},
"c-lesson15-q0-why": {
"url": "audio/c-lesson15-q0-why.m4a",
"voice": "af_heart",
"h": "d74caeddd5a0"
},
"c-lesson16-q0": {
"url": "audio/c-lesson16-q0.m4a",
"voice": "af_heart",
"h": "7fced2acec5f"
},
"c-lesson16-q0-why": {
"url": "audio/c-lesson16-q0-why.m4a",
"voice": "af_heart",
"h": "e217ec8c0b09"
},
"c-lesson17-q0": {
"url": "audio/c-lesson17-q0.m4a",
"voice": "af_heart",
"h": "82fdfaaae4e3"
},
"c-lesson17-q0-why": {
"url": "audio/c-lesson17-q0-why.m4a",
"voice": "af_heart",
"h": "09412c559d45"
},
"c-lesson18-q0": {
"url": "audio/c-lesson18-q0.m4a",
"voice": "af_heart",
"h": "2564b715c11a"
},
"c-lesson18-q0-why": {
"url": "audio/c-lesson18-q0-why.m4a",
"voice": "af_heart",
"h": "a3216c0fde2c"
},
"c-lesson19-q0": {
"url": "audio/c-lesson19-q0.m4a",
"voice": "af_heart",
"h": "a91b9bc472d4"
},
"c-lesson19-q0-why": {
"url": "audio/c-lesson19-q0-why.m4a",
"voice": "af_heart",
"h": "923ba6b1d1fb"
},
"c-lesson20-q0": {
"url": "audio/c-lesson20-q0.m4a",
"voice": "af_heart",
"h": "13a05dc899b9"
},
"c-lesson20-q0-why": {
"url": "audio/c-lesson20-q0-why.m4a",
"voice": "af_heart",
"h": "f2b39e4fd728"
},
"c-lesson21-q0": {
"url": "audio/c-lesson21-q0.m4a",
"voice": "af_heart",
"h": "83df0a388f0f"
},
"c-lesson21-q0-why": {
"url": "audio/c-lesson21-q0-why.m4a",
"voice": "af_heart",
"h": "fe2ba694e0f3"
},
"c-lesson22-q0": {
"url": "audio/c-lesson22-q0.m4a",
"voice": "af_heart",
"h": "10614f7e6637"
},
"c-lesson22-q0-why": {
"url": "audio/c-lesson22-q0-why.m4a",
"voice": "af_heart",
"h": "ee28d18eb763"
}
};
